import type { Bilingual } from "../contracts";
import wages from "../data/wages.json";
import { formatInt } from "../parse/format";

/*
 * The value of an hour of office work (plan A8, D4): role-based, the same
 * function for the quick scan (src/lib/scan/blueprint/economics.ts,
 * hourlyCostFor) and for deep research, so the same owner never sees two hour
 * values on /scan and /scan/deep.
 *
 *   gross minimum wage in force × 1.2 × (1 + CAM 2.25%) ÷ 168 hours,
 *
 * capped by the activity's average gross pay (INS, by CAEN division) when that
 * is lower. Reception, booking and admin work are paid close to the minimum
 * wage in every sector; counting doctors' or engineers' pay as reception time
 * is what made the prototypes say 56 lei (the owner review's blocker).
 * Client-safe: data comes from src/lib/deep/data/wages.json (generated by
 * scripts/deep/gen-data.ts from src/lib/scan/blueprint/wages.ts and the
 * government decision on the minimum wage).
 */

/** One calendar for every estimate: 21 working days and 168 hours a month. */
export const WORKING_DAYS_PER_MONTH = wages.workingDaysPerMonth;
export const HOURS_PER_MONTH = wages.hoursPerMonth;
export const CAM_RATE = wages.camRate;
/** Office work is paid a little above the minimum wage (×1.2). */
export const OFFICE_WAGE_FACTOR = 1.2;
export const MIN_GROSS_RON = wages.minGross.value;

export type HourValue = {
  /** Rounded to whole lei: the number shown everywhere ("32 lei/oră"). */
  value: number;
  /** Before rounding, for tests and footnotes. */
  exact: number;
  /** The monthly gross the value is built from (lei). */
  grossRon: number;
  /** CAEN division whose average pay capped the value, when it did. */
  cappedByDivision?: string;
  /** "presupunem 32 lei/oră pentru munca de birou" (shown next to the first lei figure). */
  assumption: Bilingual;
  /** The full method sentence (footnote, "Cum am calculat"). */
  basis: Bilingual;
};

const divisionGross = (caen?: string): { division: string; gross: number } | undefined => {
  const digits = (caen ?? "").replace(/\D/g, "");
  if (digits.length < 2) return undefined;
  const division = digits.slice(0, 2);
  const gross = (wages.divisions as Record<string, number>)[division];
  return typeof gross === "number" && gross > 0 ? { division, gross } : undefined;
};

/** The value of an hour of office work for a company with this CAEN code (Rev.2 or Rev.3). */
export function officeHourValue(caen?: string): HourValue {
  const base = MIN_GROSS_RON * OFFICE_WAGE_FACTOR;
  const sector = divisionGross(caen);
  const capped = sector && sector.gross < base ? sector : undefined;
  const grossRon = Math.round(capped ? capped.gross : base);
  const exact = (grossRon * (1 + CAM_RATE)) / HOURS_PER_MONTH;
  const value = Math.round(exact);
  const minRo = formatInt(MIN_GROSS_RON, "ro");
  const minEn = formatInt(MIN_GROSS_RON, "en");
  const grossRo = formatInt(grossRon, "ro");
  const grossEn = formatInt(grossRon, "en");
  const lead = capped
    ? {
        en: `The average gross pay in this activity (INS, CAEN division ${capped.division}): ${grossEn} lei a month, below 1.2 × the minimum wage`,
        ro: `Câștigul mediu brut în această activitate (INS, diviziunea CAEN ${capped.division}): ${grossRo} lei pe lună, sub 1,2 × salariul minim`,
      }
    : {
        en: `1.2 × the gross minimum wage (${minEn} lei, ${wages.minGross.decision}) = ${grossEn} lei a month`,
        ro: `1,2 × salariul minim brut (${minRo} lei, ${wages.minGross.decision}) = ${grossRo} lei pe lună`,
      };
  return {
    value,
    exact,
    grossRon,
    cappedByDivision: capped?.division,
    assumption: {
      en: `we assume ${value} lei an hour for office work`,
      ro: `presupunem ${value} lei/oră pentru munca de birou`,
    },
    basis: {
      en: `${lead.en}, plus the 2.25% employer contribution (CAM), over ${HOURS_PER_MONTH} working hours a month = ${value} lei an hour. Reception, booking and admin work are paid close to the minimum wage in every sector.`,
      ro: `${lead.ro}, plus contribuția asiguratorie pentru muncă (CAM) de 2,25%, împărțit la ${HOURS_PER_MONTH} de ore lucrate pe lună = ${value} lei pe oră. Munca de recepție, programări și birou e plătită aproape de salariul minim în orice domeniu.`,
    },
  };
}
