import type { Blueprint } from "../types";

/**
 * The plan's base case (UI refresh spec §3.9): a fictional dental clinic with no
 * website and no Google profile. The site phase, the "site online" milestone
 * and the excluded website cost all show here; use it with displayPlan() to
 * check a screen or the PDF against the reference figures.
 *
 * Generated by scripts/scan/gen-fixtures.ts from the engine: do not edit by
 * hand, run the script again after an engine change.
 */
export const BASE_CASE_BLUEPRINT: Blueprint = {
  id: "demo-dental-base-case",
  generatedAt: "2026-10-03T09:30:00.000Z",
  engine: "rules",
  target: {
    cui: "11111111",
  },
  company: {
    cui: "11111111",
    name: "CLINICA DENTARA EXEMPLU S.R.L.",
    displayName: "Clinica Dentară Exemplu SRL",
    city: "București",
    county: "București",
    caen: "8623",
    caenLabel: {
      en: "Dental practice activities",
      ro: "Activități de asistență stomatologică",
    },
    sources: ["anaf", "index"],
  },
  businessType: {
    id: "dental-clinic",
    label: {
      en: "Dental clinic",
      ro: "Clinică stomatologică",
    },
    sector: {
      en: "Healthcare",
      ro: "Sănătate",
    },
    confidence: 1,
    basis: ["Chosen by the visitor"],
  },
  presence: {
    profiles: [
      {
        platform: "google-business",
        status: "missing",
      },
    ],
  },
  scores: {
    digitalMaturity: 0,
    websiteHealth: 0,
    automationPotential: 76,
  },
  headline: {
    en: "Clinica Dentară Exemplu SRL could win back about 45 hours a month.",
    ro: "Clinica Dentară Exemplu SRL poate câștiga cam 45 de ore pe lună.",
  },
  summary: {
    en: "We found 5 tasks that can be automated, led by automatic reminders, online booking and reviews. The hours won back are worth about 1,400 RON a month, at 32 RON an hour. There is no working website yet, so a fast site with contact and booking comes first to bring in patients.",
    ro: "Am găsit 5 activități care se pot automatiza, mai ales reamintiri automate, programări online și recenzii. Orele câștigate valorează cam 1.400 lei pe lună, la 32 lei pe oră. Nu există încă un site funcțional, așa că primul pas e un site rapid, cu contact și programare, care să aducă pacienți.",
  },
  opportunities: [
    {
      id: "appointment-reminders",
      title: {
        en: "Automatic appointment reminders",
        ro: "Reamintiri automate pentru programări",
      },
      problem: {
        en: "Reception calls or texts each customer the day before their appointment, and no-shows still slip through.",
        ro: "Recepția sună sau scrie fiecărui client cu o zi înainte de programare, iar neprezentările tot apar.",
      },
      solution: {
        en: "SMS/WhatsApp reminders 24 h and 2 h before, with one-tap confirm or reschedule that updates the calendar.",
        ro: "Reamintiri pe SMS/WhatsApp cu 24 de ore și cu 2 ore înainte; clientul confirmă sau reprogramează dintr-un clic, iar calendarul se actualizează singur.",
      },
      process: "appointments",
      impact: "high",
      complexity: "low",
      hoursSavedPerMonth: {
        low: 9.7,
        high: 19,
        mid: 14,
      },
      monthlySavingsRon: {
        low: 310,
        high: 600,
        mid: 440,
      },
      setupCostRon: {
        low: 1500,
        high: 2500,
        mid: 2000,
      },
      monthlyToolCostRon: {
        low: 110,
        high: 360,
        mid: 240,
      },
      paybackMonths: {
        low: 3.1,
        high: 36,
      },
      tools: ["WhatsApp Business API", "SMS gateway", "Calendar sync"],
      assumptions: [
        {
          en: "About 420 appointments a month for a team of 5, 2–3 minutes each by hand",
          ro: "Aproximativ 420 de programări pe lună pentru o echipă de 5 persoane, câte 2–3 minute de lucru manual fiecare",
        },
        {
          en: "Most of that work handled automatically",
          ro: "Cea mai mare parte din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 32 RON/hour for office and reception work (1.2 × the minimum wage, or the sector's average pay when lower, plus CAM)",
          ro: "Cost total angajator: 32 lei pe oră pentru munca de birou și recepție (1,2 × salariul minim sau salariul mediu din domeniu, dacă e mai mic, plus CAM)",
        },
        {
          en: "Tools include about 140 RON a month of messages or AI usage (0.15–0.50 RON each)",
          ro: "Costul instrumentelor include cam 140 lei pe lună pentru mesaje sau AI (câte 0,15–0,50 lei fiecare)",
        },
        {
          en: "Fewer no-shows are a further gain we don't put a price on.",
          ro: "Mai puține neprezentări sunt un câștig în plus, pe care nu îl evaluăm în bani.",
        },
      ],
    },
    {
      id: "online-booking",
      title: {
        en: "Online booking with real availability",
        ro: "Programare online cu disponibilitate reală",
      },
      problem: {
        en: "Every booking needs a phone call or message during opening hours.",
        ro: "Fiecare programare cere un apel sau un mesaj în timpul programului.",
      },
      solution: {
        en: "A booking calendar on the website and Google profile, synced with the team's schedules, open around the clock.",
        ro: "Un calendar de programări pe site și în profilul Google, sincronizat cu programul echipei, disponibil non-stop.",
      },
      process: "appointments",
      impact: "high",
      complexity: "medium",
      hoursSavedPerMonth: {
        low: 7.3,
        high: 19,
        mid: 13,
      },
      monthlySavingsRon: {
        low: 230,
        high: 610,
        mid: 400,
      },
      setupCostRon: {
        low: 2500,
        high: 3500,
        mid: 3000,
      },
      monthlyToolCostRon: {
        low: 100,
        high: 250,
        mid: 180,
      },
      paybackMonths: {
        low: 4.9,
        high: 36,
      },
      tools: ["Booking calendar", "Google Business Profile", "Website integration"],
      assumptions: [
        {
          en: "About 420 appointments a month for a team of 5, 3–5 minutes each by hand",
          ro: "Aproximativ 420 de programări pe lună pentru o echipă de 5 persoane, câte 3–5 minute de lucru manual fiecare",
        },
        {
          en: "About half of that work handled automatically",
          ro: "Cam jumătate din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 32 RON/hour for office and reception work (1.2 × the minimum wage, or the sector's average pay when lower, plus CAM)",
          ro: "Cost total angajator: 32 lei pe oră pentru munca de birou și recepție (1,2 × salariul minim sau salariul mediu din domeniu, dacă e mai mic, plus CAM)",
        },
        {
          en: "The automatable share is the part of bookings we expect to move online.",
          ro: "Procentul automatizat este partea din programări care estimăm că se va muta online.",
        },
      ],
    },
    {
      id: "recall-reminders",
      title: {
        en: "Six-month check-up recalls",
        ro: "Reamintiri pentru controlul la șase luni",
      },
      problem: {
        en: "Patients due for a check-up or a treatment follow-up are only called when someone has time to go through the list.",
        ro: "Pacienții care au nevoie de control sau de continuarea tratamentului sunt sunați doar când cineva are timp să parcurgă lista.",
      },
      solution: {
        en: "Each patient due for a check-up gets a personal message with a booking link at the right time.",
        ro: "Fiecare pacient care trebuie să revină la control primește la momentul potrivit un mesaj personal cu link de programare.",
      },
      process: "retention",
      impact: "medium",
      complexity: "low",
      hoursSavedPerMonth: {
        low: 4,
        high: 7.9,
        mid: 5.8,
      },
      monthlySavingsRon: {
        low: 130,
        high: 250,
        mid: 190,
      },
      setupCostRon: {
        low: 1500,
        high: 2500,
        mid: 2000,
      },
      monthlyToolCostRon: {
        low: 60,
        high: 180,
        mid: 120,
      },
      paybackMonths: {
        low: 7.9,
        high: 36,
      },
      tools: ["Patient / client database", "WhatsApp / SMS", "Booking link"],
      assumptions: [
        {
          en: "About 100 check-up reminders a month for a team of 5, 3–5 minutes each by hand",
          ro: "Aproximativ 100 de reamintiri pentru control pe lună pentru o echipă de 5 persoane, câte 3–5 minute de lucru manual fiecare",
        },
        {
          en: "Most of that work handled automatically",
          ro: "Cea mai mare parte din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 32 RON/hour for office and reception work (1.2 × the minimum wage, or the sector's average pay when lower, plus CAM)",
          ro: "Cost total angajator: 32 lei pe oră pentru munca de birou și recepție (1,2 × salariul minim sau salariul mediu din domeniu, dacă e mai mic, plus CAM)",
        },
        {
          en: "Tools include about 20 RON a month of messages or AI usage (0.10–0.30 RON each)",
          ro: "Costul instrumentelor include cam 20 lei pe lună pentru mesaje sau AI (câte 0,10–0,30 lei fiecare)",
        },
      ],
    },
    {
      id: "ai-assistant",
      title: {
        en: "AI patient assistant",
        ro: "Asistent AI pentru pacienți",
      },
      problem: {
        en: "The team answers the same questions about prices, hours, availability and location many times a day, and messages sent after hours wait until morning.",
        ro: "Echipa răspunde de multe ori pe zi la aceleași întrebări despre prețuri, program, disponibilitate și locație, iar mesajele trimise după program așteaptă până dimineața.",
      },
      solution: {
        en: "An assistant on the website and WhatsApp, trained on your prices and FAQ, answers instantly in Romanian and English and hands over to a person when needed.",
        ro: "Un asistent pe site și pe WhatsApp, pregătit cu prețurile și întrebările tale frecvente, răspunde imediat în română și engleză și transferă conversația unui coleg când e nevoie.",
      },
      process: "customer-service",
      impact: "high",
      complexity: "medium",
      hoursSavedPerMonth: {
        low: 3.3,
        high: 10,
        mid: 6.3,
      },
      monthlySavingsRon: {
        low: 110,
        high: 320,
        mid: 200,
      },
      setupCostRon: {
        low: 3000,
        high: 6000,
        mid: 4500,
      },
      monthlyToolCostRon: {
        low: 110,
        high: 350,
        mid: 230,
      },
      paybackMonths: {
        low: 14.3,
        high: 36,
      },
      tools: ["AI assistant (Claude)", "Website chat", "WhatsApp Business API"],
      assumptions: [
        {
          en: "About 250 incoming questions a month for a team of 5, 2–4 minutes each by hand",
          ro: "Aproximativ 250 de întrebări primite pe lună pentru o echipă de 5 persoane, câte 2–4 minute de lucru manual fiecare",
        },
        {
          en: "About half of that work handled automatically",
          ro: "Cam jumătate din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 32 RON/hour for office and reception work (1.2 × the minimum wage, or the sector's average pay when lower, plus CAM)",
          ro: "Cost total angajator: 32 lei pe oră pentru munca de birou și recepție (1,2 × salariul minim sau salariul mediu din domeniu, dacă e mai mic, plus CAM)",
        },
        {
          en: "Tools include about 30 RON a month of messages or AI usage (0.05–0.20 RON each)",
          ro: "Costul instrumentelor include cam 30 lei pe lună pentru mesaje sau AI (câte 0,05–0,20 lei fiecare)",
        },
      ],
    },
    {
      id: "review-requests",
      title: {
        en: "Review requests after each visit",
        ro: "Cereri de recenzii după fiecare vizită",
      },
      problem: {
        en: "Happy customers rarely leave a Google review unless asked, and asking each one by hand takes time.",
        ro: "Clienții mulțumiți lasă rar o recenzie pe Google dacă nu li se cere, iar să-i rogi pe fiecare în parte durează.",
      },
      solution: {
        en: "An automatic message after the visit with a direct review link; unhappy replies go privately to the manager.",
        ro: "Un mesaj automat după vizită, cu link direct pentru recenzie; răspunsurile negative ajung doar la manager, nu în public.",
      },
      process: "reputation",
      impact: "medium",
      complexity: "low",
      hoursSavedPerMonth: {
        low: 4.7,
        high: 8.7,
        mid: 6.6,
      },
      monthlySavingsRon: {
        low: 150,
        high: 280,
        mid: 210,
      },
      setupCostRon: {
        low: 1500,
        high: 2500,
        mid: 2000,
      },
      monthlyToolCostRon: {
        low: 60,
        high: 190,
        mid: 130,
      },
      paybackMonths: {
        low: 6.8,
        high: 36,
      },
      tools: ["WhatsApp / SMS", "Google Business Profile"],
      assumptions: [
        {
          en: "About 210 post-visit follow-ups a month for a team of 5, 1.5–2.5 minutes each by hand",
          ro: "Aproximativ 210 mesaje după vizită pe lună pentru o echipă de 5 persoane, câte 1,5–2,5 minute de lucru manual fiecare",
        },
        {
          en: "Most of that work handled automatically",
          ro: "Cea mai mare parte din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 32 RON/hour for office and reception work (1.2 × the minimum wage, or the sector's average pay when lower, plus CAM)",
          ro: "Cost total angajator: 32 lei pe oră pentru munca de birou și recepție (1,2 × salariul minim sau salariul mediu din domeniu, dacă e mai mic, plus CAM)",
        },
        {
          en: "Tools include about 30 RON a month of messages or AI usage (0.05–0.20 RON each)",
          ro: "Costul instrumentelor include cam 30 lei pe lună pentru mesaje sau AI (câte 0,05–0,20 lei fiecare)",
        },
        {
          en: "Hours are what the same follow-ups would cost by hand; the main gain is more reviews, which we don't put a price on.",
          ro: "Orele reprezintă costul acelorași mesaje trimise manual; câștigul principal sunt recenziile în plus, pe care nu le evaluăm în bani.",
        },
      ],
    },
  ],
  websiteActions: [],
  totals: {
    hoursSavedPerMonth: {
      low: 29,
      high: 65,
      mid: 46,
    },
    monthlySavingsRon: {
      low: 930,
      high: 2060,
      mid: 1440,
    },
    annualSavingsRon: {
      low: 11160,
      high: 24720,
      mid: 17280,
    },
    setupCostRon: {
      low: 10000,
      high: 17000,
      mid: 13500,
    },
    paybackMonths: {
      low: 6.2,
      high: 36,
    },
    breakEven: {
      month: null,
      higherVolume: 20,
      lowerVolume: null,
    },
  },
  strategies: [
    {
      id: "acquire",
      title: {
        en: "Win more patients",
        ro: "Atrage mai mulți pacienți",
      },
      summary: {
        en: "Get online with a fast website and Google profile that bring in patients.",
        ro: "Lansează un site rapid și un profil Google care să-ți aducă pacienți.",
      },
      tactics: [
        {
          en: "A fast, mobile-first website with contact and booking",
          ro: "Un site rapid, optimizat pentru mobil, cu contact și programare",
        },
        {
          en: "Review requests after each visit",
          ro: "Cereri de recenzii după fiecare vizită",
        },
      ],
      outcome: {
        label: {
          en: "more enquiries",
          ro: "mai multe solicitări",
        },
        range: {
          low: 10,
          high: 25,
        },
        unit: "%",
        basis: {
          en: "Planning assumption, not a measured result: each gap we found and you fix (no working website yet) adds a few percent more enquiries; we add them up and cap the total at 30%.",
          ro: "Ipoteză de calcul, nu un rezultat măsurat: fiecare problemă găsită pe care o rezolvi (încă nu există un site funcțional) aduce câteva procente în plus la solicitări; le adunăm și plafonăm totalul la 30%.",
        },
      },
      implementation: "high",
      timeToValueMonths: {
        low: 2,
        high: 4,
      },
      investmentLevel: 2,
      investmentRon: {
        low: 6600,
        high: 11200,
        mid: 8900,
      },
      opportunityIds: ["review-requests"],
      recommended: true,
      startReason: "no-site",
    },
    {
      id: "automate",
      title: {
        en: "Automate the front desk",
        ro: "Automatizează recepția",
      },
      summary: {
        en: "Take routine work off the team, starting with automatic appointment reminders.",
        ro: "Scapă echipa de munca repetitivă, începând cu reamintiri automate pentru programări.",
      },
      tactics: [
        {
          en: "Automatic appointment reminders",
          ro: "Reamintiri automate pentru programări",
        },
        {
          en: "Online booking with real availability",
          ro: "Programare online cu disponibilitate reală",
        },
        {
          en: "Six-month check-up recalls",
          ro: "Reamintiri pentru controlul la șase luni",
        },
      ],
      outcome: {
        label: {
          en: "hours won back a month",
          ro: "ore câștigate pe lună",
        },
        range: {
          low: 21,
          high: 46,
        },
        unit: "hours",
        basis: {
          en: "Sum of the automations in this plan (3), each from its stated volumes and minutes per task.",
          ro: "Suma automatizărilor din acest plan (3), fiecare calculată din volumele și minutele pe sarcină declarate.",
        },
      },
      implementation: "medium",
      timeToValueMonths: {
        low: 2,
        high: 3,
      },
      investmentLevel: 2,
      investmentRon: {
        low: 5500,
        high: 8500,
        mid: 7000,
      },
      opportunityIds: ["appointment-reminders", "online-booking", "recall-reminders"],
      recommended: false,
    },
    {
      id: "assist",
      title: {
        en: "AI patient assistant",
        ro: "Asistent AI pentru pacienți",
      },
      summary: {
        en: "Answer routine questions instantly, 24/7, on the website and WhatsApp.",
        ro: "Răspunde imediat, non-stop, la întrebările de rutină, pe site și pe WhatsApp.",
      },
      tactics: [
        {
          en: "24/7 answers on the website and WhatsApp",
          ro: "Răspunsuri non-stop pe site și pe WhatsApp",
        },
        {
          en: "Answers from your own FAQ and price list",
          ro: "Răspunsuri pe baza întrebărilor frecvente și a prețurilor tale",
        },
        {
          en: "Booking straight from the chat",
          ro: "Programare direct din chat",
        },
        {
          en: "Romanian and English",
          ro: "În română și engleză",
        },
      ],
      outcome: {
        label: {
          en: "of questions answered automatically",
          ro: "din întrebări primesc răspuns automat",
        },
        range: {
          low: 40,
          high: 60,
        },
        unit: "%",
        basis: {
          en: "Planning assumption: the share of incoming questions that are routine for a dental clinic (prices, hours, availability, location) and can be answered from your FAQ.",
          ro: "Ipoteză de calcul: ponderea întrebărilor de rutină (prețuri, program, disponibilitate, locație) pentru o afacere de tipul „Clinică stomatologică”, la care se poate răspunde pe baza întrebărilor frecvente.",
        },
      },
      implementation: "medium",
      timeToValueMonths: {
        low: 1,
        high: 2,
      },
      investmentLevel: 2,
      investmentRon: {
        low: 3000,
        high: 6000,
        mid: 4500,
      },
      opportunityIds: ["ai-assistant"],
      recommended: false,
    },
  ],
  roadmap: [
    {
      key: "foundation",
      startMonth: 1,
      endMonth: 1,
      stage: {
        en: "Foundation",
        ro: "Bazele",
      },
      tag: "essential",
      title: {
        en: "New website and Google profile",
        ro: "Site nou și profil Google",
      },
      items: [
        {
          en: "A fast, mobile-first website with contact and booking (a bigger website is quoted after we talk)",
          ro: "Un site rapid, optimizat pentru mobil, cu contact și programare (pentru un site mai mare facem oferta după discuție)",
        },
        {
          en: "Claim and complete your Google Business Profile",
          ro: "Revendică și completează profilul Google Business",
        },
      ],
      opportunityIds: [],
      websiteCostRon: {
        low: 5100,
        high: 8700,
        mid: 6900,
      },
    },
    {
      key: "automation",
      startMonth: 2,
      endMonth: 3,
      stage: {
        en: "Automation",
        ro: "Automatizare",
      },
      tag: "high-impact",
      title: {
        en: "Automatic booking and reminders",
        ro: "Programări și reamintiri automate",
      },
      items: [
        {
          en: "Automatic appointment reminders",
          ro: "Reamintiri automate pentru programări",
        },
        {
          en: "Online booking with real availability",
          ro: "Programare online cu disponibilitate reală",
        },
        {
          en: "Six-month check-up recalls",
          ro: "Reamintiri pentru controlul la șase luni",
        },
      ],
      opportunityIds: ["appointment-reminders", "online-booking", "recall-reminders"],
    },
    {
      key: "assistant",
      startMonth: 3,
      endMonth: 4,
      stage: {
        en: "AI assistant",
        ro: "Asistent AI",
      },
      tag: "high-impact",
      title: {
        en: "Website and WhatsApp assistant",
        ro: "Asistent pe site și WhatsApp",
      },
      items: [
        {
          en: "AI patient assistant",
          ro: "Asistent AI pentru pacienți",
        },
        {
          en: "Your FAQ, prices and tone of voice prepared for the assistant",
          ro: "Întrebările frecvente, prețurile și stilul de comunicare, pregătite pentru asistent",
        },
        {
          en: "Handover to a person on WhatsApp or email",
          ro: "Preluarea conversației de către un coleg, pe WhatsApp sau e-mail",
        },
      ],
      opportunityIds: ["ai-assistant"],
    },
    {
      key: "growth",
      startMonth: 4,
      endMonth: 6,
      stage: {
        en: "Growth",
        ro: "Creștere",
      },
      tag: "growth",
      title: {
        en: "Reviews",
        ro: "Recenzii",
      },
      items: [
        {
          en: "Review requests after each visit",
          ro: "Cereri de recenzii după fiecare vizită",
        },
      ],
      opportunityIds: ["review-requests"],
    },
  ],
  projection: [
    {
      month: 1,
      cumulativeSavingsRon: {
        low: 0,
        high: 0,
        mid: 0,
      },
      cumulativeCostRon: {
        low: 0,
        high: 0,
        mid: 0,
      },
    },
    {
      month: 2,
      cumulativeSavingsRon: {
        low: 0,
        high: 0,
        mid: 0,
      },
      cumulativeCostRon: {
        low: 5500,
        high: 8500,
        mid: 7000,
      },
    },
    {
      month: 3,
      cumulativeSavingsRon: {
        low: 340,
        high: 730,
        mid: 520,
      },
      cumulativeCostRon: {
        low: 8770,
        high: 15290,
        mid: 12040,
      },
    },
    {
      month: 4,
      cumulativeSavingsRon: {
        low: 1060,
        high: 2350,
        mid: 1650,
      },
      cumulativeCostRon: {
        low: 10650,
        high: 18930,
        mid: 14810,
      },
    },
    {
      month: 5,
      cumulativeSavingsRon: {
        low: 1920,
        high: 4270,
        mid: 2980,
      },
      cumulativeCostRon: {
        low: 11090,
        high: 20260,
        mid: 15710,
      },
    },
    {
      month: 6,
      cumulativeSavingsRon: {
        low: 2850,
        high: 6330,
        mid: 4420,
      },
      cumulativeCostRon: {
        low: 11530,
        high: 21590,
        mid: 16610,
      },
    },
    {
      month: 7,
      cumulativeSavingsRon: {
        low: 3780,
        high: 8390,
        mid: 5860,
      },
      cumulativeCostRon: {
        low: 11970,
        high: 22920,
        mid: 17510,
      },
    },
    {
      month: 8,
      cumulativeSavingsRon: {
        low: 4710,
        high: 10450,
        mid: 7300,
      },
      cumulativeCostRon: {
        low: 12410,
        high: 24250,
        mid: 18410,
      },
    },
    {
      month: 9,
      cumulativeSavingsRon: {
        low: 5640,
        high: 12510,
        mid: 8740,
      },
      cumulativeCostRon: {
        low: 12850,
        high: 25580,
        mid: 19310,
      },
    },
    {
      month: 10,
      cumulativeSavingsRon: {
        low: 6570,
        high: 14570,
        mid: 10180,
      },
      cumulativeCostRon: {
        low: 13290,
        high: 26910,
        mid: 20210,
      },
    },
    {
      month: 11,
      cumulativeSavingsRon: {
        low: 7500,
        high: 16630,
        mid: 11620,
      },
      cumulativeCostRon: {
        low: 13730,
        high: 28240,
        mid: 21110,
      },
    },
    {
      month: 12,
      cumulativeSavingsRon: {
        low: 8430,
        high: 18690,
        mid: 13060,
      },
      cumulativeCostRon: {
        low: 14170,
        high: 29570,
        mid: 22010,
      },
    },
    {
      month: 13,
      cumulativeSavingsRon: {
        low: 9360,
        high: 20750,
        mid: 14500,
      },
      cumulativeCostRon: {
        low: 14610,
        high: 30900,
        mid: 22910,
      },
    },
    {
      month: 14,
      cumulativeSavingsRon: {
        low: 10290,
        high: 22810,
        mid: 15940,
      },
      cumulativeCostRon: {
        low: 15050,
        high: 32230,
        mid: 23810,
      },
    },
    {
      month: 15,
      cumulativeSavingsRon: {
        low: 11220,
        high: 24870,
        mid: 17380,
      },
      cumulativeCostRon: {
        low: 15490,
        high: 33560,
        mid: 24710,
      },
    },
    {
      month: 16,
      cumulativeSavingsRon: {
        low: 12150,
        high: 26930,
        mid: 18820,
      },
      cumulativeCostRon: {
        low: 15930,
        high: 34890,
        mid: 25610,
      },
    },
    {
      month: 17,
      cumulativeSavingsRon: {
        low: 13080,
        high: 28990,
        mid: 20260,
      },
      cumulativeCostRon: {
        low: 16370,
        high: 36220,
        mid: 26510,
      },
    },
    {
      month: 18,
      cumulativeSavingsRon: {
        low: 14010,
        high: 31050,
        mid: 21700,
      },
      cumulativeCostRon: {
        low: 16810,
        high: 37550,
        mid: 27410,
      },
    },
    {
      month: 19,
      cumulativeSavingsRon: {
        low: 14940,
        high: 33110,
        mid: 23140,
      },
      cumulativeCostRon: {
        low: 17250,
        high: 38880,
        mid: 28310,
      },
    },
    {
      month: 20,
      cumulativeSavingsRon: {
        low: 15870,
        high: 35170,
        mid: 24580,
      },
      cumulativeCostRon: {
        low: 17690,
        high: 40210,
        mid: 29210,
      },
    },
    {
      month: 21,
      cumulativeSavingsRon: {
        low: 16800,
        high: 37230,
        mid: 26020,
      },
      cumulativeCostRon: {
        low: 18130,
        high: 41540,
        mid: 30110,
      },
    },
    {
      month: 22,
      cumulativeSavingsRon: {
        low: 17730,
        high: 39290,
        mid: 27460,
      },
      cumulativeCostRon: {
        low: 18570,
        high: 42870,
        mid: 31010,
      },
    },
    {
      month: 23,
      cumulativeSavingsRon: {
        low: 18660,
        high: 41350,
        mid: 28900,
      },
      cumulativeCostRon: {
        low: 19010,
        high: 44200,
        mid: 31910,
      },
    },
    {
      month: 24,
      cumulativeSavingsRon: {
        low: 19590,
        high: 43410,
        mid: 30340,
      },
      cumulativeCostRon: {
        low: 19450,
        high: 45530,
        mid: 32810,
      },
    },
  ],
  offer: {
    planId: "project",
    title: {
      en: "The project alone, no plan",
      ro: "Doar proiectul, fără abonament",
    },
    why: {
      en: "We don't suggest a plan: on the base estimate the automations don't pay back within 24 months even without one, so we add no monthly cost. We confirm the volumes on the call. If you'd like us to keep the website healthy, Starter is 290 RON a month.",
      ro: "Nu propunem un abonament: cu estimarea de bază, automatizările nu se recuperează în 24 de luni nici fără el, deci nu adăugăm un cost lunar. Confirmăm volumele la discuție. Dacă vrei să ținem site-ul în formă, Starter costă 290 lei pe lună.",
    },
    includes: [],
    priceNote: {
      en: "A fixed price for the project, agreed before we start",
      ro: "Preț fix pentru proiect, stabilit înainte să începem",
    },
  },
  assumptions: {
    hourlyCostRon: 32,
    hourlyCostBasis: {
      en: "1.2 × the gross minimum wage (4,325 lei, HG nr. 146/2026 (Monitorul Oficial, 13.03.2026)) = 5,190 lei a month, plus the 2.25% employer contribution (CAM), over 168 working hours a month = 32 lei an hour. Reception, booking and admin work are paid close to the minimum wage in every sector.",
      ro: "1,2 × salariul minim brut (4.325 lei, HG nr. 146/2026 (Monitorul Oficial, 13.03.2026)) = 5.190 lei pe lună, plus contribuția asiguratorie pentru muncă (CAM) de 2,25%, împărțit la 168 de ore lucrate pe lună = 32 lei pe oră. Munca de recepție, programări și birou e plătită aproape de salariul minim în orice domeniu.",
    },
    teamSize: {
      low: 3,
      high: 7,
    },
    simulation: {
      teamSize: 5,
      hourlyCostRon: 32,
      volumeFactor: 1,
    },
    notes: [
      {
        en: "Team size is an estimate, not data: 3–7 people for a typical dental clinic. We lowered the estimate a little because the business has no website. Set your real team size in the simulation.",
        ro: "Mărimea echipei e o estimare, nu o cifră reală: 3–7 persoane pentru o afacere de tipul „Clinică stomatologică”. Am redus puțin estimarea pentru că firma nu are site. Poți pune numărul real de oameni în simulare.",
      },
      {
        en: "Volumes are typical for a dental clinic of this size, not measured; each automation lists its own.",
        ro: "Volumele sunt tipice pentru o afacere de tipul „Clinică stomatologică” de această mărime, nu sunt măsurate; fiecare automatizare își arată propriile volume.",
      },
      {
        en: "Costs are a one-off setup plus monthly tools from Vortex Hub's price book (RON); the Vortex Hub plan fee is separate.",
        ro: "Costurile includ implementarea, plătită o singură dată, și instrumentele lunare, conform listei de prețuri Vortex Hub (în lei); abonamentul Vortex Hub se plătește separat.",
      },
      {
        en: "Projection: setup is paid when its phase of the plan starts; the hours won back start the month after, at half the first month and in full after that.",
        ro: "Proiecție: implementarea se plătește la începutul etapei din plan; orele câștigate încep din luna următoare, pe jumătate în prima lună și integral după aceea.",
      },
    ],
  },
  disclaimer: {
    en: "Estimates, not guarantees. Based on public data (ANAF, the Trade Register, your website), INS average earnings (July 2026), typical volumes for this kind of business and Vortex's price book. Final figures come from a short discovery call.",
    ro: "Estimări, nu garanții. Calculele folosesc date publice (ANAF, Registrul Comerțului, site-ul tău), câștigul salarial mediu INS (iulie 2026), volume tipice pentru acest tip de afacere și lista de prețuri Vortex. Cifrele finale le stabilim împreună, după o scurtă discuție de evaluare.",
  },
};
