import type { Blueprint } from "../types";

/**
 * The plan's base case (UI refresh spec §3.9): a fictional dental clinic with no
 * website and no Google profile. The site phase, the "site online" milestone
 * and the excluded website cost all show here; use it with displayPlan() to
 * check a screen or the PDF against the reference figures.
 *
 * Generated by scripts/scan/gen-fixtures.ts from the engine: do not edit by
 * hand, run the script again after an engine change.
 */
export const BASE_CASE_BLUEPRINT: Blueprint = {
  id: "demo-dental-base-case",
  generatedAt: "2026-10-03T09:30:00.000Z",
  engine: "rules",
  target: {
    cui: "11111111",
  },
  company: {
    cui: "11111111",
    name: "CLINICA DENTARA EXEMPLU S.R.L.",
    displayName: "Clinica Dentară Exemplu SRL",
    city: "București",
    county: "București",
    caen: "8623",
    caenLabel: {
      en: "Dental practice activities",
      ro: "Activități de asistență stomatologică",
    },
    sources: ["anaf", "index"],
  },
  businessType: {
    id: "dental-clinic",
    label: {
      en: "Dental clinic",
      ro: "Clinică stomatologică",
    },
    sector: {
      en: "Healthcare",
      ro: "Sănătate",
    },
    confidence: 1,
    basis: ["Chosen by the visitor"],
  },
  presence: {
    profiles: [
      {
        platform: "google-business",
        status: "missing",
      },
    ],
  },
  scores: {
    digitalMaturity: 0,
    websiteHealth: 0,
    automationPotential: 81,
  },
  headline: {
    en: "Clinica Dentară Exemplu SRL could win back about 50 hours a month.",
    ro: "Clinica Dentară Exemplu SRL poate câștiga cam 50 de ore pe lună.",
  },
  summary: {
    en: "We found 6 tasks that can be automated, led by automatic reminders, online booking and reviews. The hours won back are worth about 2,900 RON a month, at 59 RON an hour. There is no working website yet, so a fast site with contact and booking comes first to bring in patients.",
    ro: "Am găsit 6 activități care se pot automatiza, mai ales reamintiri automate, programări online și recenzii. Orele câștigate valorează cam 2.900 lei pe lună, la 59 lei pe oră. Nu există încă un site funcțional, așa că primul pas e un site rapid, cu contact și programare, care să aducă pacienți.",
  },
  opportunities: [
    {
      id: "appointment-reminders",
      title: {
        en: "Automatic appointment reminders",
        ro: "Reamintiri automate pentru programări",
      },
      problem: {
        en: "Reception calls or texts each customer the day before their appointment, and no-shows still slip through.",
        ro: "Recepția sună sau scrie fiecărui client cu o zi înainte de programare, iar neprezentările tot apar.",
      },
      solution: {
        en: "SMS/WhatsApp reminders 24 h and 2 h before, with one-tap confirm or reschedule that updates the calendar.",
        ro: "Reamintiri pe SMS/WhatsApp cu 24 de ore și cu 2 ore înainte; clientul confirmă sau reprogramează dintr-un clic, iar calendarul se actualizează singur.",
      },
      process: "appointments",
      impact: "high",
      complexity: "low",
      hoursSavedPerMonth: {
        low: 9.7,
        high: 19,
        mid: 14,
      },
      monthlySavingsRon: {
        low: 570,
        high: 1110,
        mid: 820,
      },
      setupCostRon: {
        low: 1200,
        high: 2500,
        mid: 1850,
      },
      monthlyToolCostRon: {
        low: 110,
        high: 360,
        mid: 240,
      },
      paybackMonths: {
        low: 1.2,
        high: 11.9,
      },
      tools: ["WhatsApp Business API", "SMS gateway", "Calendar sync"],
      assumptions: [
        {
          en: "About 420 appointments a month for a team of 5, 2–3 minutes each by hand",
          ro: "Aproximativ 420 de programări pe lună pentru o echipă de 5 persoane, câte 2–3 minute de lucru manual fiecare",
        },
        {
          en: "Most of that work handled automatically",
          ro: "Cea mai mare parte din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 59 RON/hour (INS average earnings, July 2026)",
          ro: "Cost total angajator: 59 lei pe oră (câștigul salarial mediu INS, iulie 2026)",
        },
        {
          en: "Tools include about 140 RON a month of messages or AI usage (0.15–0.50 RON each)",
          ro: "Costul instrumentelor include cam 140 lei pe lună pentru mesaje sau AI (câte 0,15–0,50 lei fiecare)",
        },
        {
          en: "Fewer no-shows are a further gain we don't put a price on.",
          ro: "Mai puține neprezentări sunt un câștig în plus, pe care nu îl evaluăm în bani.",
        },
      ],
    },
    {
      id: "online-booking",
      title: {
        en: "Online booking with real availability",
        ro: "Programare online cu disponibilitate reală",
      },
      problem: {
        en: "Every booking needs a phone call or message during opening hours.",
        ro: "Fiecare programare cere un apel sau un mesaj în timpul programului.",
      },
      solution: {
        en: "A booking calendar on the website and Google profile, synced with the team's schedules, open around the clock.",
        ro: "Un calendar de programări pe site și în profilul Google, sincronizat cu programul echipei, disponibil non-stop.",
      },
      process: "appointments",
      impact: "high",
      complexity: "medium",
      hoursSavedPerMonth: {
        low: 7.3,
        high: 19,
        mid: 13,
      },
      monthlySavingsRon: {
        low: 430,
        high: 1130,
        mid: 740,
      },
      setupCostRon: {
        low: 3000,
        high: 6000,
        mid: 4500,
      },
      monthlyToolCostRon: {
        low: 100,
        high: 250,
        mid: 180,
      },
      paybackMonths: {
        low: 2.9,
        high: 33.3,
      },
      tools: ["Booking calendar", "Google Business Profile", "Website integration"],
      assumptions: [
        {
          en: "About 420 appointments a month for a team of 5, 3–5 minutes each by hand",
          ro: "Aproximativ 420 de programări pe lună pentru o echipă de 5 persoane, câte 3–5 minute de lucru manual fiecare",
        },
        {
          en: "About half of that work handled automatically",
          ro: "Cam jumătate din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 59 RON/hour (INS average earnings, July 2026)",
          ro: "Cost total angajator: 59 lei pe oră (câștigul salarial mediu INS, iulie 2026)",
        },
        {
          en: "The automatable share is the part of bookings we expect to move online.",
          ro: "Procentul automatizat este partea din programări care estimăm că se va muta online.",
        },
      ],
    },
    {
      id: "recall-reminders",
      title: {
        en: "Six-month check-up recalls",
        ro: "Reamintiri pentru controlul la șase luni",
      },
      problem: {
        en: "Patients due for a check-up or a treatment follow-up are only called when someone has time to go through the list.",
        ro: "Pacienții care au nevoie de control sau de continuarea tratamentului sunt sunați doar când cineva are timp să parcurgă lista.",
      },
      solution: {
        en: "Each patient due for a check-up gets a personal message with a booking link at the right time.",
        ro: "Fiecare pacient care trebuie să revină la control primește la momentul potrivit un mesaj personal cu link de programare.",
      },
      process: "retention",
      impact: "medium",
      complexity: "low",
      hoursSavedPerMonth: {
        low: 4,
        high: 7.9,
        mid: 5.8,
      },
      monthlySavingsRon: {
        low: 240,
        high: 470,
        mid: 340,
      },
      setupCostRon: {
        low: 1200,
        high: 2500,
        mid: 1850,
      },
      monthlyToolCostRon: {
        low: 60,
        high: 180,
        mid: 120,
      },
      paybackMonths: {
        low: 2.9,
        high: 36,
      },
      tools: ["Patient / client database", "WhatsApp / SMS", "Booking link"],
      assumptions: [
        {
          en: "About 100 check-up reminders a month for a team of 5, 3–5 minutes each by hand",
          ro: "Aproximativ 100 de reamintiri pentru control pe lună pentru o echipă de 5 persoane, câte 3–5 minute de lucru manual fiecare",
        },
        {
          en: "Most of that work handled automatically",
          ro: "Cea mai mare parte din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 59 RON/hour (INS average earnings, July 2026)",
          ro: "Cost total angajator: 59 lei pe oră (câștigul salarial mediu INS, iulie 2026)",
        },
        {
          en: "Tools include about 20 RON a month of messages or AI usage (0.10–0.30 RON each)",
          ro: "Costul instrumentelor include cam 20 lei pe lună pentru mesaje sau AI (câte 0,10–0,30 lei fiecare)",
        },
      ],
    },
    {
      id: "ai-assistant",
      title: {
        en: "AI patient assistant",
        ro: "Asistent AI pentru pacienți",
      },
      problem: {
        en: "The team answers the same questions about prices, hours, availability and location many times a day, and messages sent after hours wait until morning.",
        ro: "Echipa răspunde de multe ori pe zi la aceleași întrebări despre prețuri, program, disponibilitate și locație, iar mesajele trimise după program așteaptă până dimineața.",
      },
      solution: {
        en: "An assistant on the website and WhatsApp, trained on your prices and FAQ, answers instantly in Romanian and English and hands over to a person when needed.",
        ro: "Un asistent pe site și pe WhatsApp, pregătit cu prețurile și întrebările tale frecvente, răspunde imediat în română și engleză și transferă conversația unui coleg când e nevoie.",
      },
      process: "customer-service",
      impact: "high",
      complexity: "medium",
      hoursSavedPerMonth: {
        low: 3.3,
        high: 10,
        mid: 6.3,
      },
      monthlySavingsRon: {
        low: 200,
        high: 590,
        mid: 370,
      },
      setupCostRon: {
        low: 3000,
        high: 6000,
        mid: 4500,
      },
      monthlyToolCostRon: {
        low: 110,
        high: 350,
        mid: 230,
      },
      paybackMonths: {
        low: 6.3,
        high: 36,
      },
      tools: ["AI assistant (Claude)", "Website chat", "WhatsApp Business API"],
      assumptions: [
        {
          en: "About 250 incoming questions a month for a team of 5, 2–4 minutes each by hand",
          ro: "Aproximativ 250 de întrebări primite pe lună pentru o echipă de 5 persoane, câte 2–4 minute de lucru manual fiecare",
        },
        {
          en: "About half of that work handled automatically",
          ro: "Cam jumătate din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 59 RON/hour (INS average earnings, July 2026)",
          ro: "Cost total angajator: 59 lei pe oră (câștigul salarial mediu INS, iulie 2026)",
        },
        {
          en: "Tools include about 30 RON a month of messages or AI usage (0.05–0.20 RON each)",
          ro: "Costul instrumentelor include cam 30 lei pe lună pentru mesaje sau AI (câte 0,05–0,20 lei fiecare)",
        },
      ],
    },
    {
      id: "review-requests",
      title: {
        en: "Review requests after each visit",
        ro: "Cereri de recenzii după fiecare vizită",
      },
      problem: {
        en: "Happy customers rarely leave a Google review unless asked, and asking each one by hand takes time.",
        ro: "Clienții mulțumiți lasă rar o recenzie pe Google dacă nu li se cere, iar să-i rogi pe fiecare în parte durează.",
      },
      solution: {
        en: "An automatic message after the visit with a direct review link; unhappy replies go privately to the manager.",
        ro: "Un mesaj automat după vizită, cu link direct pentru recenzie; răspunsurile negative ajung doar la manager, nu în public.",
      },
      process: "reputation",
      impact: "medium",
      complexity: "low",
      hoursSavedPerMonth: {
        low: 4.7,
        high: 8.7,
        mid: 6.6,
      },
      monthlySavingsRon: {
        low: 280,
        high: 510,
        mid: 390,
      },
      setupCostRon: {
        low: 1200,
        high: 2500,
        mid: 1850,
      },
      monthlyToolCostRon: {
        low: 60,
        high: 190,
        mid: 130,
      },
      paybackMonths: {
        low: 2.7,
        high: 27.8,
      },
      tools: ["WhatsApp / SMS", "Google Business Profile"],
      assumptions: [
        {
          en: "About 210 post-visit follow-ups a month for a team of 5, 1.5–2.5 minutes each by hand",
          ro: "Aproximativ 210 mesaje după vizită pe lună pentru o echipă de 5 persoane, câte 1,5–2,5 minute de lucru manual fiecare",
        },
        {
          en: "Most of that work handled automatically",
          ro: "Cea mai mare parte din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 59 RON/hour (INS average earnings, July 2026)",
          ro: "Cost total angajator: 59 lei pe oră (câștigul salarial mediu INS, iulie 2026)",
        },
        {
          en: "Tools include about 30 RON a month of messages or AI usage (0.05–0.20 RON each)",
          ro: "Costul instrumentelor include cam 30 lei pe lună pentru mesaje sau AI (câte 0,05–0,20 lei fiecare)",
        },
        {
          en: "Hours are what the same follow-ups would cost by hand; the main gain is more reviews, which we don't put a price on.",
          ro: "Orele reprezintă costul acelorași mesaje trimise manual; câștigul principal sunt recenziile în plus, pe care nu le evaluăm în bani.",
        },
      ],
    },
    {
      id: "lead-capture-crm",
      title: {
        en: "Every enquiry in one shared list",
        ro: "Toate cererile într-o listă comună",
      },
      problem: {
        en: "Enquiries arrive by phone, email, WhatsApp and forms and are tracked in notebooks or inboxes, so follow-ups get forgotten.",
        ro: "Solicitările vin pe telefon, e-mail, WhatsApp și formulare și sunt ținute în agende sau în căsuța de e-mail, așa că revenirile la clienți se uită.",
      },
      solution: {
        en: "Forms, emails and WhatsApp messages create contacts and deals automatically, with follow-up reminders and a clear pipeline.",
        ro: "Formularele, e-mailurile și mesajele WhatsApp creează automat contacte și oportunități de vânzare, cu reamintiri pentru revenire și o evidență clară a fiecărei etape.",
      },
      process: "sales",
      impact: "high",
      complexity: "medium",
      hoursSavedPerMonth: {
        low: 2.2,
        high: 6.7,
        mid: 4.2,
      },
      monthlySavingsRon: {
        low: 130,
        high: 390,
        mid: 250,
      },
      setupCostRon: {
        low: 3000,
        high: 6000,
        mid: 4500,
      },
      monthlyToolCostRon: {
        low: 100,
        high: 250,
        mid: 180,
      },
      paybackMonths: {
        low: 10.3,
        high: 36,
      },
      tools: ["HubSpot / Pipedrive", "WhatsApp Business", "Website forms"],
      assumptions: [
        {
          en: "About 65 enquiries a month for a team of 5, 5–10 minutes each by hand",
          ro: "Aproximativ 65 de solicitări pe lună pentru o echipă de 5 persoane, câte 5–10 minute de lucru manual fiecare",
        },
        {
          en: "About half of that work handled automatically",
          ro: "Cam jumătate din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 59 RON/hour (INS average earnings, July 2026)",
          ro: "Cost total angajator: 59 lei pe oră (câștigul salarial mediu INS, iulie 2026)",
        },
      ],
    },
  ],
  websiteActions: [],
  totals: {
    hoursSavedPerMonth: {
      low: 31,
      high: 71,
      mid: 50,
    },
    monthlySavingsRon: {
      low: 1850,
      high: 4200,
      mid: 2910,
    },
    annualSavingsRon: {
      low: 22200,
      high: 50400,
      mid: 34920,
    },
    setupCostRon: {
      low: 12600,
      high: 25500,
      mid: 19050,
    },
    paybackMonths: {
      low: 3.4,
      high: 36,
    },
    breakEven: {
      month: 14,
      higherVolume: 12,
      lowerVolume: 19,
    },
  },
  strategies: [
    {
      id: "acquire",
      title: {
        en: "Win more patients",
        ro: "Atrage mai mulți pacienți",
      },
      summary: {
        en: "Get online with a fast website and Google profile that bring in patients.",
        ro: "Lansează un site rapid și un profil Google care să-ți aducă pacienți.",
      },
      tactics: [
        {
          en: "A fast, mobile-first website with contact and booking",
          ro: "Un site rapid, optimizat pentru mobil, cu contact și programare",
        },
        {
          en: "Review requests after each visit",
          ro: "Cereri de recenzii după fiecare vizită",
        },
        {
          en: "Every enquiry in one shared list",
          ro: "Toate cererile într-o listă comună",
        },
      ],
      outcome: {
        label: {
          en: "more enquiries",
          ro: "mai multe solicitări",
        },
        range: {
          low: 10,
          high: 25,
        },
        unit: "%",
        basis: {
          en: "Planning assumption, not a measured result: each gap we found and you fix (no working website yet) adds a few percent more enquiries; we add them up and cap the total at 30%.",
          ro: "Ipoteză de calcul, nu un rezultat măsurat: fiecare problemă găsită pe care o rezolvi (încă nu există un site funcțional) aduce câteva procente în plus la solicitări; le adunăm și plafonăm totalul la 30%.",
        },
      },
      implementation: "high",
      timeToValueMonths: {
        low: 2,
        high: 4,
      },
      investmentLevel: 3,
      investmentRon: {
        low: 10700,
        high: 25000,
        mid: 17850,
      },
      opportunityIds: ["review-requests", "lead-capture-crm"],
      recommended: true,
      startReason: "no-site",
    },
    {
      id: "automate",
      title: {
        en: "Automate the front desk",
        ro: "Automatizează recepția",
      },
      summary: {
        en: "Take routine work off the team, starting with automatic appointment reminders.",
        ro: "Scapă echipa de munca repetitivă, începând cu reamintiri automate pentru programări.",
      },
      tactics: [
        {
          en: "Automatic appointment reminders",
          ro: "Reamintiri automate pentru programări",
        },
        {
          en: "Online booking with real availability",
          ro: "Programare online cu disponibilitate reală",
        },
        {
          en: "Six-month check-up recalls",
          ro: "Reamintiri pentru controlul la șase luni",
        },
      ],
      outcome: {
        label: {
          en: "hours won back a month",
          ro: "ore câștigate pe lună",
        },
        range: {
          low: 21,
          high: 46,
        },
        unit: "hours",
        basis: {
          en: "Sum of the automations in this plan (3), each from its stated volumes and minutes per task.",
          ro: "Suma automatizărilor din acest plan (3), fiecare calculată din volumele și minutele pe sarcină declarate.",
        },
      },
      implementation: "medium",
      timeToValueMonths: {
        low: 2,
        high: 3,
      },
      investmentLevel: 2,
      investmentRon: {
        low: 5400,
        high: 11000,
        mid: 8200,
      },
      opportunityIds: ["appointment-reminders", "online-booking", "recall-reminders"],
      recommended: false,
    },
    {
      id: "assist",
      title: {
        en: "AI patient assistant",
        ro: "Asistent AI pentru pacienți",
      },
      summary: {
        en: "Answer routine questions instantly, 24/7, on the website and WhatsApp.",
        ro: "Răspunde imediat, non-stop, la întrebările de rutină, pe site și pe WhatsApp.",
      },
      tactics: [
        {
          en: "24/7 answers on the website and WhatsApp",
          ro: "Răspunsuri non-stop pe site și pe WhatsApp",
        },
        {
          en: "Answers from your own FAQ and price list",
          ro: "Răspunsuri pe baza întrebărilor frecvente și a prețurilor tale",
        },
        {
          en: "Booking straight from the chat",
          ro: "Programare direct din chat",
        },
        {
          en: "Romanian and English",
          ro: "În română și engleză",
        },
      ],
      outcome: {
        label: {
          en: "of questions answered automatically",
          ro: "din întrebări primesc răspuns automat",
        },
        range: {
          low: 40,
          high: 60,
        },
        unit: "%",
        basis: {
          en: "Planning assumption: the share of incoming questions that are routine for a dental clinic (prices, hours, availability, location) and can be answered from your FAQ.",
          ro: "Ipoteză de calcul: ponderea întrebărilor de rutină (prețuri, program, disponibilitate, locație) pentru o afacere de tipul „Clinică stomatologică”, la care se poate răspunde pe baza întrebărilor frecvente.",
        },
      },
      implementation: "medium",
      timeToValueMonths: {
        low: 1,
        high: 2,
      },
      investmentLevel: 2,
      investmentRon: {
        low: 3000,
        high: 6000,
        mid: 4500,
      },
      opportunityIds: ["ai-assistant"],
      recommended: false,
    },
  ],
  roadmap: [
    {
      key: "foundation",
      startMonth: 1,
      endMonth: 1,
      stage: {
        en: "Foundation",
        ro: "Bazele",
      },
      tag: "essential",
      title: {
        en: "New website and Google profile",
        ro: "Site nou și profil Google",
      },
      items: [
        {
          en: "A fast, mobile-first website with contact and booking",
          ro: "Un site rapid, optimizat pentru mobil, cu contact și programare",
        },
        {
          en: "Claim and complete your Google Business Profile",
          ro: "Revendică și completează profilul Google Business",
        },
      ],
      opportunityIds: [],
      websiteCostRon: {
        low: 6500,
        high: 16500,
        mid: 11500,
      },
    },
    {
      key: "automation",
      startMonth: 2,
      endMonth: 3,
      stage: {
        en: "Automation",
        ro: "Automatizare",
      },
      tag: "high-impact",
      title: {
        en: "Automatic booking and reminders",
        ro: "Programări și reamintiri automate",
      },
      items: [
        {
          en: "Automatic appointment reminders",
          ro: "Reamintiri automate pentru programări",
        },
        {
          en: "Online booking with real availability",
          ro: "Programare online cu disponibilitate reală",
        },
        {
          en: "Six-month check-up recalls",
          ro: "Reamintiri pentru controlul la șase luni",
        },
      ],
      opportunityIds: ["appointment-reminders", "online-booking", "recall-reminders"],
    },
    {
      key: "assistant",
      startMonth: 3,
      endMonth: 4,
      stage: {
        en: "AI assistant",
        ro: "Asistent AI",
      },
      tag: "high-impact",
      title: {
        en: "Website and WhatsApp assistant",
        ro: "Asistent pe site și WhatsApp",
      },
      items: [
        {
          en: "AI patient assistant",
          ro: "Asistent AI pentru pacienți",
        },
        {
          en: "Your FAQ, prices and tone of voice prepared for the assistant",
          ro: "Întrebările frecvente, prețurile și stilul de comunicare, pregătite pentru asistent",
        },
        {
          en: "Handover to a person on WhatsApp or email",
          ro: "Preluarea conversației de către un coleg, pe WhatsApp sau e-mail",
        },
      ],
      opportunityIds: ["ai-assistant"],
    },
    {
      key: "growth",
      startMonth: 4,
      endMonth: 6,
      stage: {
        en: "Growth",
        ro: "Creștere",
      },
      tag: "growth",
      title: {
        en: "Reviews and one list of enquiries",
        ro: "Recenzii și evidența solicitărilor",
      },
      items: [
        {
          en: "Review requests after each visit",
          ro: "Cereri de recenzii după fiecare vizită",
        },
        {
          en: "Every enquiry in one shared list",
          ro: "Toate cererile într-o listă comună",
        },
      ],
      opportunityIds: ["review-requests", "lead-capture-crm"],
    },
  ],
  projection: [
    {
      month: 1,
      cumulativeSavingsRon: {
        low: 0,
        high: 0,
        mid: 0,
      },
      cumulativeCostRon: {
        low: 0,
        high: 0,
        mid: 0,
      },
    },
    {
      month: 2,
      cumulativeSavingsRon: {
        low: 0,
        high: 0,
        mid: 0,
      },
      cumulativeCostRon: {
        low: 5400,
        high: 11000,
        mid: 8200,
      },
    },
    {
      month: 3,
      cumulativeSavingsRon: {
        low: 620,
        high: 1360,
        mid: 950,
      },
      cumulativeCostRon: {
        low: 8670,
        high: 17790,
        mid: 13240,
      },
    },
    {
      month: 4,
      cumulativeSavingsRon: {
        low: 1960,
        high: 4360,
        mid: 3040,
      },
      cumulativeCostRon: {
        low: 13250,
        high: 27430,
        mid: 20360,
      },
    },
    {
      month: 5,
      cumulativeSavingsRon: {
        low: 3610,
        high: 8110,
        mid: 5630,
      },
      cumulativeCostRon: {
        low: 13790,
        high: 29010,
        mid: 21440,
      },
    },
    {
      month: 6,
      cumulativeSavingsRon: {
        low: 5460,
        high: 12310,
        mid: 8540,
      },
      cumulativeCostRon: {
        low: 14330,
        high: 30590,
        mid: 22520,
      },
    },
    {
      month: 7,
      cumulativeSavingsRon: {
        low: 7310,
        high: 16510,
        mid: 11450,
      },
      cumulativeCostRon: {
        low: 14870,
        high: 32170,
        mid: 23600,
      },
    },
    {
      month: 8,
      cumulativeSavingsRon: {
        low: 9160,
        high: 20710,
        mid: 14360,
      },
      cumulativeCostRon: {
        low: 15410,
        high: 33750,
        mid: 24680,
      },
    },
    {
      month: 9,
      cumulativeSavingsRon: {
        low: 11010,
        high: 24910,
        mid: 17270,
      },
      cumulativeCostRon: {
        low: 15950,
        high: 35330,
        mid: 25760,
      },
    },
    {
      month: 10,
      cumulativeSavingsRon: {
        low: 12860,
        high: 29110,
        mid: 20180,
      },
      cumulativeCostRon: {
        low: 16490,
        high: 36910,
        mid: 26840,
      },
    },
    {
      month: 11,
      cumulativeSavingsRon: {
        low: 14710,
        high: 33310,
        mid: 23090,
      },
      cumulativeCostRon: {
        low: 17030,
        high: 38490,
        mid: 27920,
      },
    },
    {
      month: 12,
      cumulativeSavingsRon: {
        low: 16560,
        high: 37510,
        mid: 26000,
      },
      cumulativeCostRon: {
        low: 17570,
        high: 40070,
        mid: 29000,
      },
    },
    {
      month: 13,
      cumulativeSavingsRon: {
        low: 18410,
        high: 41710,
        mid: 28910,
      },
      cumulativeCostRon: {
        low: 18110,
        high: 41650,
        mid: 30080,
      },
    },
    {
      month: 14,
      cumulativeSavingsRon: {
        low: 20260,
        high: 45910,
        mid: 31820,
      },
      cumulativeCostRon: {
        low: 18650,
        high: 43230,
        mid: 31160,
      },
    },
    {
      month: 15,
      cumulativeSavingsRon: {
        low: 22110,
        high: 50110,
        mid: 34730,
      },
      cumulativeCostRon: {
        low: 19190,
        high: 44810,
        mid: 32240,
      },
    },
    {
      month: 16,
      cumulativeSavingsRon: {
        low: 23960,
        high: 54310,
        mid: 37640,
      },
      cumulativeCostRon: {
        low: 19730,
        high: 46390,
        mid: 33320,
      },
    },
    {
      month: 17,
      cumulativeSavingsRon: {
        low: 25810,
        high: 58510,
        mid: 40550,
      },
      cumulativeCostRon: {
        low: 20270,
        high: 47970,
        mid: 34400,
      },
    },
    {
      month: 18,
      cumulativeSavingsRon: {
        low: 27660,
        high: 62710,
        mid: 43460,
      },
      cumulativeCostRon: {
        low: 20810,
        high: 49550,
        mid: 35480,
      },
    },
    {
      month: 19,
      cumulativeSavingsRon: {
        low: 29510,
        high: 66910,
        mid: 46370,
      },
      cumulativeCostRon: {
        low: 21350,
        high: 51130,
        mid: 36560,
      },
    },
    {
      month: 20,
      cumulativeSavingsRon: {
        low: 31360,
        high: 71110,
        mid: 49280,
      },
      cumulativeCostRon: {
        low: 21890,
        high: 52710,
        mid: 37640,
      },
    },
    {
      month: 21,
      cumulativeSavingsRon: {
        low: 33210,
        high: 75310,
        mid: 52190,
      },
      cumulativeCostRon: {
        low: 22430,
        high: 54290,
        mid: 38720,
      },
    },
    {
      month: 22,
      cumulativeSavingsRon: {
        low: 35060,
        high: 79510,
        mid: 55100,
      },
      cumulativeCostRon: {
        low: 22970,
        high: 55870,
        mid: 39800,
      },
    },
    {
      month: 23,
      cumulativeSavingsRon: {
        low: 36910,
        high: 83710,
        mid: 58010,
      },
      cumulativeCostRon: {
        low: 23510,
        high: 57450,
        mid: 40880,
      },
    },
    {
      month: 24,
      cumulativeSavingsRon: {
        low: 38760,
        high: 87910,
        mid: 60920,
      },
      cumulativeCostRon: {
        low: 24050,
        high: 59030,
        mid: 41960,
      },
    },
  ],
  offer: {
    planId: "pro",
    title: {
      en: "Pro",
      ro: "Pro",
    },
    why: {
      en: "The plan has 4 stages; with Pro we build them with you and keep them running.",
      ro: "Planul are 4 etape; cu Pro le construim împreună și le ținem în funcțiune.",
    },
    includes: [
      {
        en: "Hands-on help building the 4 stages of the plan",
        ro: "Ajutor practic la construirea celor 4 etape din plan",
      },
      {
        en: "Unlimited live support from our team while they run",
        ro: "Suport live nelimitat din partea echipei noastre, cât timp rulează",
      },
      {
        en: "A direct priority line to us",
        ro: "Legătură directă, cu prioritate, cu echipa noastră",
      },
    ],
    priceNote: {
      en: "1,000 RON a month, plus the setup (fixed price after a call)",
      ro: "1.000 lei pe lună, plus implementarea (preț fix după discuție)",
    },
  },
  assumptions: {
    hourlyCostRon: 59,
    hourlyCostBasis: {
      en: "Your sector (human health, CAEN division 86) averages 11,137 RON gross a month (INS, July 2026), above the national average, so we use the national 9,709 RON because the work being automated is routine admin, plus the 2.25% employer contribution (CAM), over 168 working hours a month = 59 RON/hour. Source: INS press release no. 229 of 11 Sept 2026; TEMPO table FOM107G.",
      ro: "Sectorul tău (sănătate umană, diviziunea CAEN 86) are un câștig mediu brut de 11.137 lei pe lună (INS, iulie 2026), peste media națională; folosim totuși media națională de 9.709 lei, pentru că se automatizează muncă administrativă de rutină, plus contribuția asiguratorie pentru muncă (CAM) de 2,25%, împărțit la 168 de ore lucrate pe lună = 59 lei pe oră. Sursa: comunicatul INS nr. 229 din 11 sept. 2026; tabelul TEMPO FOM107G.",
    },
    teamSize: {
      low: 3,
      high: 7,
    },
    simulation: {
      teamSize: 5,
      hourlyCostRon: 59,
      volumeFactor: 1,
    },
    notes: [
      {
        en: "Team size is an estimate, not data: 3–7 people for a typical dental clinic. We lowered the estimate a little because the business has no website. Set your real team size in the simulation.",
        ro: "Mărimea echipei e o estimare, nu o cifră reală: 3–7 persoane pentru o afacere de tipul „Clinică stomatologică”. Am redus puțin estimarea pentru că firma nu are site. Poți pune numărul real de oameni în simulare.",
      },
      {
        en: "Volumes are typical for a dental clinic of this size, not measured; each automation lists its own.",
        ro: "Volumele sunt tipice pentru o afacere de tipul „Clinică stomatologică” de această mărime, nu sunt măsurate; fiecare automatizare își arată propriile volume.",
      },
      {
        en: "Costs are a one-off setup plus monthly tools from Vortex Hub's price book (RON, excluding VAT); the Vortex Hub plan fee is separate.",
        ro: "Costurile includ implementarea, plătită o singură dată, și instrumentele lunare, conform listei de prețuri Vortex Hub (lei, fără TVA); abonamentul Vortex Hub se plătește separat.",
      },
      {
        en: "Projection: setup is paid when its phase of the plan starts; the hours won back start the month after, at half the first month and in full after that.",
        ro: "Proiecție: implementarea se plătește la începutul etapei din plan; orele câștigate încep din luna următoare, pe jumătate în prima lună și integral după aceea.",
      },
    ],
  },
  disclaimer: {
    en: "Estimates, not guarantees. Based on public data (ANAF, the Trade Register, your website), INS average earnings (July 2026), typical volumes for this kind of business and Vortex's price book. Final figures come from a short discovery call.",
    ro: "Estimări, nu garanții. Calculele folosesc date publice (ANAF, Registrul Comerțului, site-ul tău), câștigul salarial mediu INS (iulie 2026), volume tipice pentru acest tip de afacere și lista de prețuri Vortex. Cifrele finale le stabilim împreună, după o scurtă discuție de evaluare.",
  },
};
