import type { Blueprint } from "../types";

/**
 * A realistic blueprint for designing and testing the scan report and the PDF
 * without running a scan (a fictional dental clinic in Timișoara, shown as
 * "Date de exemplu"). Also served at /scan?demo=overview. The ANAF address keeps the
 * registry's cedilla letters on purpose: the screens fix them with
 * withCommaBelow (src/lib/scan/localize.ts).
 *
 * Generated by scripts/scan/gen-fixtures.ts from the engine: do not edit by
 * hand, run the script again after an engine change.
 */
export const SAMPLE_BLUEPRINT: Blueprint = {
  id: "demo-dental-timisoara",
  generatedAt: "2026-10-03T09:30:00.000Z",
  engine: "rules",
  target: {
    cui: "12345678",
  },
  company: {
    cui: "12345678",
    name: "DENTAL SMILE CLINIC S.R.L.",
    displayName: "Dental Smile Clinic SRL",
    regNo: "J35/0000/2015",
    legalForm: "SOCIETATE COMERCIALĂ CU RĂSPUNDERE LIMITATĂ",
    address: "JUD. TIMIŞ, MUN. TIMIŞOARA, BD. REVOLUŢIEI 1989, NR. 10",
    county: "Timiș",
    city: "Timișoara",
    phone: "+40 256 000 000",
    caen: "8623",
    caenLabel: {
      en: "Dental practice activities",
      ro: "Activități de asistență stomatologică",
    },
    registeredAt: "2015-03-12",
    vatPayer: false,
    inactive: false,
    website: "https://dentalsmile-example.ro",
    sources: ["anaf", "index"],
  },
  audit: {
    url: "https://dentalsmile-example.ro",
    finalUrl: "https://dentalsmile-example.ro/",
    host: "dentalsmile-example.ro",
    fetchedAt: "2026-10-03T09:29:40.000Z",
    reachable: true,
    https: true,
    statusCode: 200,
    responseMs: 1840,
    pages: [
      {
        url: "https://dentalsmile-example.ro/",
        status: 200,
        title: "Dental Smile Clinic – Stomatologie Timișoara",
      },
      {
        url: "https://dentalsmile-example.ro/servicii",
        status: 200,
        title: "Servicii",
      },
      {
        url: "https://dentalsmile-example.ro/contact",
        status: 200,
        title: "Contact",
      },
    ],
    meta: {
      title: "Dental Smile Clinic – Stomatologie Timișoara",
      lang: "ro",
    },
    technologies: [
      {
        name: "WordPress",
        category: "cms",
        confidence: 0.95,
      },
      {
        name: "Elementor",
        category: "builder",
        confidence: 0.9,
      },
      {
        name: "Google Analytics 4",
        category: "analytics",
        confidence: 0.9,
      },
    ],
    signals: {
      hasContactForm: true,
      hasPhone: true,
      hasEmail: true,
      hasWhatsApp: false,
      hasLiveChat: false,
      hasOnlineBooking: false,
      hasEcommerce: false,
      hasCookieConsent: false,
      hasAnalytics: true,
      hasMarketingPixel: false,
      hasStructuredData: false,
      hasNewsletter: false,
      hasBlog: false,
      languages: ["ro"],
      socialLinks: ["https://facebook.com/dentalsmile-example"],
      cuiOnSite: "12345678",
    },
    scores: {
      performance: 46,
      seo: 62,
      accessibility: 71,
      security: 58,
      conversion: 44,
      overall: 56,
    },
    pagespeed: {
      strategy: "mobile",
      performance: 46,
      accessibility: 71,
      bestPractices: 78,
      seo: 83,
      lcpMs: 4600,
      cls: 0.12,
      tbtMs: 690,
    },
    findings: [
      {
        id: "conversion.no-online-booking",
        category: "conversion",
        severity: "high",
        title: {
          en: "No online booking",
          ro: "Fără programare online",
        },
        detail: {
          en: "Patients can only book by phone or the contact form, so bookings stop when the reception is busy or closed.",
          ro: "Pacienții se pot programa doar telefonic sau prin formular, deci programările se opresc când recepția e ocupată sau închisă.",
        },
        recommendation: {
          en: "We add a booking calendar with real free slots and automatic confirmations.",
          ro: "Adăugăm un calendar de programări cu locuri libere reale și confirmări automate.",
        },
        effort: "medium",
      },
      {
        id: "performance.slow-lcp",
        category: "performance",
        severity: "high",
        title: {
          en: "Slow first screen on mobile",
          ro: "Primul ecran se încarcă greu pe mobil",
        },
        detail: {
          en: "The largest element appears after 4.6 s on a mid-range phone (good is under 2.5 s).",
          ro: "Elementul principal apare după 4,6 s pe un telefon mediu (ideal sub 2,5 s).",
        },
        recommendation: {
          en: "We shrink the main image and load what's visible first; the other scripts wait until after.",
          ro: "Micșorăm poza principală și încărcăm întâi ce se vede; restul scripturilor vin după.",
        },
        evidence: "LCP 4.6 s (Lighthouse, mobile)",
        effort: "quick",
      },
      {
        id: "security.no-cookie-consent",
        category: "security",
        severity: "high",
        title: {
          en: "Visitor tracking without cookie consent",
          ro: "Urmărirea vizitatorilor fără acord pentru cookie-uri",
        },
        detail: {
          en: "Google Analytics loads before the visitor agrees, which goes against GDPR and the cookie law.",
          ro: "Google Analytics se încarcă înainte de acordul vizitatorului, ceea ce contravine GDPR și legii cookie-urilor.",
        },
        recommendation: {
          en: "We add a consent banner and start the visitor statistics only after the visitor agrees.",
          ro: "Adăugăm un banner de acord și pornim statisticile de trafic doar după ce vizitatorul acceptă.",
        },
        effort: "quick",
      },
      {
        id: "seo.no-structured-data",
        category: "seo",
        severity: "medium",
        title: {
          en: "Google doesn't get your business details",
          ro: "Google nu primește datele firmei",
        },
        detail: {
          en: "The site doesn't give Google its hours, address and phone in a form it reads directly, so they don't show in the results.",
          ro: "Site-ul nu îi dă lui Google programul, adresa și telefonul într-o formă pe care o citește direct, deci nu apar în rezultate.",
        },
        recommendation: {
          en: "We give Google your address, hours, phone and services in a form it reads directly.",
          ro: "Îi dăm lui Google adresa, programul, telefonul și serviciile, într-o formă pe care o citește direct.",
        },
        effort: "quick",
      },
      {
        id: "conversion.no-whatsapp",
        category: "conversion",
        severity: "low",
        title: {
          en: "No WhatsApp contact",
          ro: "Fără contact pe WhatsApp",
        },
        detail: {
          en: "Most patients prefer messaging to calling; there is no click-to-chat option.",
          ro: "Mulți pacienți preferă mesajele în locul apelurilor; nu există opțiune de chat rapid.",
        },
        recommendation: {
          en: "We add a WhatsApp Business button with quick replies for prices and availability.",
          ro: "Adăugăm un buton WhatsApp Business, cu răspunsuri rapide pentru prețuri și disponibilitate.",
        },
        effort: "quick",
      },
    ],
  },
  businessType: {
    id: "dental-clinic",
    label: {
      en: "Dental clinic",
      ro: "Clinică stomatologică",
    },
    sector: {
      en: "Healthcare",
      ro: "Sănătate",
    },
    confidence: 0.95,
    basis: ["CAEN 8623 (Dental practice activities)", "Words on the site: stomatolog, dental"],
  },
  presence: {
    profiles: [
      {
        platform: "website",
        status: "active",
        url: "https://dentalsmile-example.ro",
        metric: {
          label: {
            en: "Pages analysed",
            ro: "Pagini analizate",
          },
          value: "3",
        },
      },
      {
        platform: "google-business",
        status: "detected",
        url: "https://maps.google.com/?cid=0",
      },
      {
        platform: "facebook",
        status: "active",
        url: "https://facebook.com/dentalsmile-example",
      },
      {
        platform: "instagram",
        status: "missing",
      },
      {
        platform: "linkedin",
        status: "missing",
      },
      {
        platform: "youtube",
        status: "missing",
      },
    ],
  },
  competitors: [
    {
      cui: "23456789",
      name: "Clinica Exemplu Nord SRL",
      city: "Timișoara",
      website: "https://nord-example.ro",
      websiteScore: 71,
    },
    {
      cui: "34567890",
      name: "Clinica Exemplu Centru SRL",
      city: "Timișoara",
      website: "https://centru-example.ro",
      websiteScore: 64,
    },
    {
      cui: "45678901",
      name: "Clinica Exemplu Vest SRL",
      city: "Timișoara",
    },
  ],
  scores: {
    digitalMaturity: 47,
    websiteHealth: 56,
    automationPotential: 75,
  },
  headline: {
    en: "Dental Smile Clinic SRL could win back about 55 hours a month.",
    ro: "Dental Smile Clinic SRL poate câștiga cam 55 de ore pe lună.",
  },
  summary: {
    en: "We found 5 tasks that can be automated, led by automatic reminders, online booking and reviews. The hours won back are worth about 1,700 RON a month, at 32 RON an hour. The website scores 56 out of 100; we found 5 issues worth fixing first (starting with “slow first screen on mobile”) that could turn more visits into patients.",
    ro: "Am găsit 5 activități care se pot automatiza, mai ales reamintiri automate, programări online și recenzii. Orele câștigate valorează cam 1.700 lei pe lună, la 32 lei pe oră. Site-ul are scorul 56 din 100; am găsit 5 probleme de rezolvat întâi (prima: „primul ecran se încarcă greu pe mobil”); rezolvate, pot transforma mai multe vizite în pacienți.",
  },
  opportunities: [
    {
      id: "appointment-reminders",
      title: {
        en: "Automatic appointment reminders",
        ro: "Reamintiri automate pentru programări",
      },
      problem: {
        en: "Reception calls or texts each customer the day before their appointment, and no-shows still slip through.",
        ro: "Recepția sună sau scrie fiecărui client cu o zi înainte de programare, iar neprezentările tot apar.",
      },
      solution: {
        en: "SMS/WhatsApp reminders 24 h and 2 h before, with one-tap confirm or reschedule that updates the calendar.",
        ro: "Reamintiri pe SMS/WhatsApp cu 24 de ore și cu 2 ore înainte; clientul confirmă sau reprogramează dintr-un clic, iar calendarul se actualizează singur.",
      },
      process: "appointments",
      impact: "high",
      complexity: "low",
      hoursSavedPerMonth: {
        low: 12,
        high: 23,
        mid: 17,
      },
      monthlySavingsRon: {
        low: 370,
        high: 720,
        mid: 530,
      },
      setupCostRon: {
        low: 1200,
        high: 2500,
        mid: 1850,
      },
      monthlyToolCostRon: {
        low: 130,
        high: 400,
        mid: 260,
      },
      paybackMonths: {
        low: 2,
        high: 36,
      },
      tools: ["WhatsApp Business API", "SMS gateway", "Calendar sync"],
      assumptions: [
        {
          en: "About 500 appointments a month for a team of 6, 2–3 minutes each by hand",
          ro: "Aproximativ 500 de programări pe lună pentru o echipă de 6 persoane, câte 2–3 minute de lucru manual fiecare",
        },
        {
          en: "Most of that work handled automatically",
          ro: "Cea mai mare parte din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 32 RON/hour for office and reception work (1.2 × the minimum wage, or the sector's average pay when lower, plus CAM)",
          ro: "Cost total angajator: 32 lei pe oră pentru munca de birou și recepție (1,2 × salariul minim sau salariul mediu din domeniu, dacă e mai mic, plus CAM)",
        },
        {
          en: "Tools include about 160 RON a month of messages or AI usage (0.15–0.50 RON each)",
          ro: "Costul instrumentelor include cam 160 lei pe lună pentru mesaje sau AI (câte 0,15–0,50 lei fiecare)",
        },
        {
          en: "Fewer no-shows are a further gain we don't put a price on.",
          ro: "Mai puține neprezentări sunt un câștig în plus, pe care nu îl evaluăm în bani.",
        },
      ],
    },
    {
      id: "online-booking",
      title: {
        en: "Online booking with real availability",
        ro: "Programare online cu disponibilitate reală",
      },
      problem: {
        en: "Every booking needs a phone call or message during opening hours.",
        ro: "Fiecare programare cere un apel sau un mesaj în timpul programului.",
      },
      solution: {
        en: "A booking calendar on the website and Google profile, synced with the team's schedules, open around the clock.",
        ro: "Un calendar de programări pe site și în profilul Google, sincronizat cu programul echipei, disponibil non-stop.",
      },
      process: "appointments",
      impact: "high",
      complexity: "medium",
      hoursSavedPerMonth: {
        low: 8.8,
        high: 23,
        mid: 15,
      },
      monthlySavingsRon: {
        low: 280,
        high: 730,
        mid: 480,
      },
      setupCostRon: {
        low: 3000,
        high: 6000,
        mid: 4500,
      },
      monthlyToolCostRon: {
        low: 100,
        high: 250,
        mid: 180,
      },
      paybackMonths: {
        low: 4.8,
        high: 36,
      },
      tools: ["Booking calendar", "Google Business Profile", "Website integration"],
      assumptions: [
        {
          en: "About 500 appointments a month for a team of 6, 3–5 minutes each by hand",
          ro: "Aproximativ 500 de programări pe lună pentru o echipă de 6 persoane, câte 3–5 minute de lucru manual fiecare",
        },
        {
          en: "About half of that work handled automatically",
          ro: "Cam jumătate din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 32 RON/hour for office and reception work (1.2 × the minimum wage, or the sector's average pay when lower, plus CAM)",
          ro: "Cost total angajator: 32 lei pe oră pentru munca de birou și recepție (1,2 × salariul minim sau salariul mediu din domeniu, dacă e mai mic, plus CAM)",
        },
        {
          en: "The automatable share is the part of bookings we expect to move online.",
          ro: "Procentul automatizat este partea din programări care estimăm că se va muta online.",
        },
      ],
    },
    {
      id: "recall-reminders",
      title: {
        en: "Six-month check-up recalls",
        ro: "Reamintiri pentru controlul la șase luni",
      },
      problem: {
        en: "Patients due for a check-up or a treatment follow-up are only called when someone has time to go through the list.",
        ro: "Pacienții care au nevoie de control sau de continuarea tratamentului sunt sunați doar când cineva are timp să parcurgă lista.",
      },
      solution: {
        en: "Each patient due for a check-up gets a personal message with a booking link at the right time.",
        ro: "Fiecare pacient care trebuie să revină la control primește la momentul potrivit un mesaj personal cu link de programare.",
      },
      process: "retention",
      impact: "medium",
      complexity: "low",
      hoursSavedPerMonth: {
        low: 4.8,
        high: 9.5,
        mid: 7,
      },
      monthlySavingsRon: {
        low: 150,
        high: 300,
        mid: 220,
      },
      setupCostRon: {
        low: 1200,
        high: 2500,
        mid: 1850,
      },
      monthlyToolCostRon: {
        low: 60,
        high: 190,
        mid: 120,
      },
      paybackMonths: {
        low: 5,
        high: 36,
      },
      tools: ["Patient / client database", "WhatsApp / SMS", "Booking link"],
      assumptions: [
        {
          en: "About 120 check-up reminders a month for a team of 6, 3–5 minutes each by hand",
          ro: "Aproximativ 120 de reamintiri pentru control pe lună pentru o echipă de 6 persoane, câte 3–5 minute de lucru manual fiecare",
        },
        {
          en: "Most of that work handled automatically",
          ro: "Cea mai mare parte din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 32 RON/hour for office and reception work (1.2 × the minimum wage, or the sector's average pay when lower, plus CAM)",
          ro: "Cost total angajator: 32 lei pe oră pentru munca de birou și recepție (1,2 × salariul minim sau salariul mediu din domeniu, dacă e mai mic, plus CAM)",
        },
        {
          en: "Tools include about 20 RON a month of messages or AI usage (0.10–0.30 RON each)",
          ro: "Costul instrumentelor include cam 20 lei pe lună pentru mesaje sau AI (câte 0,10–0,30 lei fiecare)",
        },
      ],
    },
    {
      id: "ai-assistant",
      title: {
        en: "AI patient assistant",
        ro: "Asistent AI pentru pacienți",
      },
      problem: {
        en: "The team answers the same questions about prices, hours, availability and location many times a day, and messages sent after hours wait until morning.",
        ro: "Echipa răspunde de multe ori pe zi la aceleași întrebări despre prețuri, program, disponibilitate și locație, iar mesajele trimise după program așteaptă până dimineața.",
      },
      solution: {
        en: "An assistant on the website and WhatsApp, trained on your prices and FAQ, answers instantly in Romanian and English and hands over to a person when needed.",
        ro: "Un asistent pe site și pe WhatsApp, pregătit cu prețurile și întrebările tale frecvente, răspunde imediat în română și engleză și transferă conversația unui coleg când e nevoie.",
      },
      process: "customer-service",
      impact: "high",
      complexity: "medium",
      hoursSavedPerMonth: {
        low: 4,
        high: 12,
        mid: 7.5,
      },
      monthlySavingsRon: {
        low: 130,
        high: 380,
        mid: 240,
      },
      setupCostRon: {
        low: 3000,
        high: 6000,
        mid: 4500,
      },
      monthlyToolCostRon: {
        low: 120,
        high: 360,
        mid: 240,
      },
      paybackMonths: {
        low: 11.5,
        high: 36,
      },
      tools: ["AI assistant (Claude)", "Website chat", "WhatsApp Business API"],
      assumptions: [
        {
          en: "About 300 incoming questions a month for a team of 6, 2–4 minutes each by hand",
          ro: "Aproximativ 300 de întrebări primite pe lună pentru o echipă de 6 persoane, câte 2–4 minute de lucru manual fiecare",
        },
        {
          en: "About half of that work handled automatically",
          ro: "Cam jumătate din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 32 RON/hour for office and reception work (1.2 × the minimum wage, or the sector's average pay when lower, plus CAM)",
          ro: "Cost total angajator: 32 lei pe oră pentru munca de birou și recepție (1,2 × salariul minim sau salariul mediu din domeniu, dacă e mai mic, plus CAM)",
        },
        {
          en: "Tools include about 40 RON a month of messages or AI usage (0.05–0.20 RON each)",
          ro: "Costul instrumentelor include cam 40 lei pe lună pentru mesaje sau AI (câte 0,05–0,20 lei fiecare)",
        },
      ],
    },
    {
      id: "review-requests",
      title: {
        en: "Review requests after each visit",
        ro: "Cereri de recenzii după fiecare vizită",
      },
      problem: {
        en: "Happy customers rarely leave a Google review unless asked, and asking each one by hand takes time.",
        ro: "Clienții mulțumiți lasă rar o recenzie pe Google dacă nu li se cere, iar să-i rogi pe fiecare în parte durează.",
      },
      solution: {
        en: "An automatic message after the visit with a direct review link; unhappy replies go privately to the manager.",
        ro: "Un mesaj automat după vizită, cu link direct pentru recenzie; răspunsurile negative ajung doar la manager, nu în public.",
      },
      process: "reputation",
      impact: "medium",
      complexity: "low",
      hoursSavedPerMonth: {
        low: 5.6,
        high: 10,
        mid: 7.9,
      },
      monthlySavingsRon: {
        low: 180,
        high: 330,
        mid: 250,
      },
      setupCostRon: {
        low: 1200,
        high: 2500,
        mid: 1850,
      },
      monthlyToolCostRon: {
        low: 60,
        high: 200,
        mid: 130,
      },
      paybackMonths: {
        low: 4.4,
        high: 36,
      },
      tools: ["WhatsApp / SMS", "Google Business Profile"],
      assumptions: [
        {
          en: "About 250 post-visit follow-ups a month for a team of 6, 1.5–2.5 minutes each by hand",
          ro: "Aproximativ 250 de mesaje după vizită pe lună pentru o echipă de 6 persoane, câte 1,5–2,5 minute de lucru manual fiecare",
        },
        {
          en: "Most of that work handled automatically",
          ro: "Cea mai mare parte din această muncă se face automat",
        },
        {
          en: "Loaded staff cost 32 RON/hour for office and reception work (1.2 × the minimum wage, or the sector's average pay when lower, plus CAM)",
          ro: "Cost total angajator: 32 lei pe oră pentru munca de birou și recepție (1,2 × salariul minim sau salariul mediu din domeniu, dacă e mai mic, plus CAM)",
        },
        {
          en: "Tools include about 30 RON a month of messages or AI usage (0.05–0.20 RON each)",
          ro: "Costul instrumentelor include cam 30 lei pe lună pentru mesaje sau AI (câte 0,05–0,20 lei fiecare)",
        },
        {
          en: "Hours are what the same follow-ups would cost by hand; the main gain is more reviews, which we don't put a price on.",
          ro: "Orele reprezintă costul acelorași mesaje trimise manual; câștigul principal sunt recenziile în plus, pe care nu le evaluăm în bani.",
        },
      ],
    },
  ],
  websiteActions: [
    {
      id: "performance.slow-lcp",
      category: "performance",
      severity: "high",
      title: {
        en: "Slow first screen on mobile",
        ro: "Primul ecran se încarcă greu pe mobil",
      },
      detail: {
        en: "The largest element appears after 4.6 s on a mid-range phone (good is under 2.5 s).",
        ro: "Elementul principal apare după 4,6 s pe un telefon mediu (ideal sub 2,5 s).",
      },
      recommendation: {
        en: "We shrink the main image and load what's visible first; the other scripts wait until after.",
        ro: "Micșorăm poza principală și încărcăm întâi ce se vede; restul scripturilor vin după.",
      },
      evidence: "LCP 4.6 s (Lighthouse, mobile)",
      effort: "quick",
    },
    {
      id: "security.no-cookie-consent",
      category: "security",
      severity: "high",
      title: {
        en: "Visitor tracking without cookie consent",
        ro: "Urmărirea vizitatorilor fără acord pentru cookie-uri",
      },
      detail: {
        en: "Google Analytics loads before the visitor agrees, which goes against GDPR and the cookie law.",
        ro: "Google Analytics se încarcă înainte de acordul vizitatorului, ceea ce contravine GDPR și legii cookie-urilor.",
      },
      recommendation: {
        en: "We add a consent banner and start the visitor statistics only after the visitor agrees.",
        ro: "Adăugăm un banner de acord și pornim statisticile de trafic doar după ce vizitatorul acceptă.",
      },
      effort: "quick",
    },
    {
      id: "conversion.no-online-booking",
      category: "conversion",
      severity: "high",
      title: {
        en: "No online booking",
        ro: "Fără programare online",
      },
      detail: {
        en: "Patients can only book by phone or the contact form, so bookings stop when the reception is busy or closed.",
        ro: "Pacienții se pot programa doar telefonic sau prin formular, deci programările se opresc când recepția e ocupată sau închisă.",
      },
      recommendation: {
        en: "We add a booking calendar with real free slots and automatic confirmations.",
        ro: "Adăugăm un calendar de programări cu locuri libere reale și confirmări automate.",
      },
      effort: "medium",
    },
    {
      id: "seo.no-structured-data",
      category: "seo",
      severity: "medium",
      title: {
        en: "Google doesn't get your business details",
        ro: "Google nu primește datele firmei",
      },
      detail: {
        en: "The site doesn't give Google its hours, address and phone in a form it reads directly, so they don't show in the results.",
        ro: "Site-ul nu îi dă lui Google programul, adresa și telefonul într-o formă pe care o citește direct, deci nu apar în rezultate.",
      },
      recommendation: {
        en: "We give Google your address, hours, phone and services in a form it reads directly.",
        ro: "Îi dăm lui Google adresa, programul, telefonul și serviciile, într-o formă pe care o citește direct.",
      },
      effort: "quick",
    },
    {
      id: "conversion.no-whatsapp",
      category: "conversion",
      severity: "low",
      title: {
        en: "No WhatsApp contact",
        ro: "Fără contact pe WhatsApp",
      },
      detail: {
        en: "Most patients prefer messaging to calling; there is no click-to-chat option.",
        ro: "Mulți pacienți preferă mesajele în locul apelurilor; nu există opțiune de chat rapid.",
      },
      recommendation: {
        en: "We add a WhatsApp Business button with quick replies for prices and availability.",
        ro: "Adăugăm un buton WhatsApp Business, cu răspunsuri rapide pentru prețuri și disponibilitate.",
      },
      effort: "quick",
    },
  ],
  totals: {
    hoursSavedPerMonth: {
      low: 35,
      high: 78,
      mid: 54,
    },
    monthlySavingsRon: {
      low: 1110,
      high: 2460,
      mid: 1720,
    },
    annualSavingsRon: {
      low: 13320,
      high: 29520,
      mid: 20640,
    },
    setupCostRon: {
      low: 9600,
      high: 19500,
      mid: 14550,
    },
    paybackMonths: {
      low: 4.8,
      high: 36,
    },
    breakEven: {
      month: 22,
      higherVolume: 16,
      lowerVolume: null,
    },
  },
  strategies: [
    {
      id: "acquire",
      title: {
        en: "Win more patients",
        ro: "Atrage mai mulți pacienți",
      },
      summary: {
        en: "Get found by more patients and turn more website visits into enquiries.",
        ro: "Fă-te mai ușor de găsit de pacienți și transformă mai multe vizite pe site în solicitări.",
      },
      tactics: [
        {
          en: "Faster mobile pages",
          ro: "Pagini mai rapide pe mobil",
        },
        {
          en: "Online booking around the clock",
          ro: "Programare online non-stop",
        },
        {
          en: "Quick chat on WhatsApp",
          ro: "Chat rapid pe WhatsApp",
        },
        {
          en: "Easier to find on Google and Maps",
          ro: "Mai ușor de găsit în Google și pe hartă",
        },
        {
          en: "Review requests after each visit",
          ro: "Cereri de recenzii după fiecare vizită",
        },
      ],
      outcome: {
        label: {
          en: "more enquiries",
          ro: "mai multe solicitări",
        },
        range: {
          low: 13,
          high: 29,
        },
        unit: "%",
        basis: {
          en: "Planning assumption, not a measured result: each gap we found and you fix (slow mobile pages, no online booking, no quick chat, hard to find on Google nearby, no automatic review requests) adds a few percent more enquiries; we add them up and cap the total at 30%.",
          ro: "Ipoteză de calcul, nu un rezultat măsurat: fiecare problemă găsită pe care o rezolvi (pagini lente pe mobil, fără programare online, fără chat rapid, greu de găsit în Google, în zona ta, fără cereri automate de recenzii) aduce câteva procente în plus la solicitări; le adunăm și plafonăm totalul la 30%.",
        },
      },
      implementation: "medium",
      timeToValueMonths: {
        low: 2,
        high: 4,
      },
      investmentLevel: 2,
      investmentRon: {
        low: 3900,
        high: 9000,
        mid: 6450,
      },
      opportunityIds: ["review-requests"],
      recommended: true,
      startReason: "acquire-gaps",
    },
    {
      id: "automate",
      title: {
        en: "Automate the front desk",
        ro: "Automatizează recepția",
      },
      summary: {
        en: "Take routine work off the team, starting with automatic appointment reminders.",
        ro: "Scapă echipa de munca repetitivă, începând cu reamintiri automate pentru programări.",
      },
      tactics: [
        {
          en: "Automatic appointment reminders",
          ro: "Reamintiri automate pentru programări",
        },
        {
          en: "Online booking with real availability",
          ro: "Programare online cu disponibilitate reală",
        },
        {
          en: "Six-month check-up recalls",
          ro: "Reamintiri pentru controlul la șase luni",
        },
      ],
      outcome: {
        label: {
          en: "hours won back a month",
          ro: "ore câștigate pe lună",
        },
        range: {
          low: 26,
          high: 56,
        },
        unit: "hours",
        basis: {
          en: "Sum of the automations in this plan (3), each from its stated volumes and minutes per task.",
          ro: "Suma automatizărilor din acest plan (3), fiecare calculată din volumele și minutele pe sarcină declarate.",
        },
      },
      implementation: "medium",
      timeToValueMonths: {
        low: 2,
        high: 3,
      },
      investmentLevel: 2,
      investmentRon: {
        low: 5400,
        high: 11000,
        mid: 8200,
      },
      opportunityIds: ["appointment-reminders", "online-booking", "recall-reminders"],
      recommended: false,
    },
    {
      id: "assist",
      title: {
        en: "AI patient assistant",
        ro: "Asistent AI pentru pacienți",
      },
      summary: {
        en: "Answer routine questions instantly, 24/7, on the website and WhatsApp.",
        ro: "Răspunde imediat, non-stop, la întrebările de rutină, pe site și pe WhatsApp.",
      },
      tactics: [
        {
          en: "24/7 answers on the website and WhatsApp",
          ro: "Răspunsuri non-stop pe site și pe WhatsApp",
        },
        {
          en: "Answers from your own FAQ and price list",
          ro: "Răspunsuri pe baza întrebărilor frecvente și a prețurilor tale",
        },
        {
          en: "Booking straight from the chat",
          ro: "Programare direct din chat",
        },
        {
          en: "Romanian and English",
          ro: "În română și engleză",
        },
      ],
      outcome: {
        label: {
          en: "of questions answered automatically",
          ro: "din întrebări primesc răspuns automat",
        },
        range: {
          low: 40,
          high: 60,
        },
        unit: "%",
        basis: {
          en: "Planning assumption: the share of incoming questions that are routine for a dental clinic (prices, hours, availability, location) and can be answered from your FAQ.",
          ro: "Ipoteză de calcul: ponderea întrebărilor de rutină (prețuri, program, disponibilitate, locație) pentru o afacere de tipul „Clinică stomatologică”, la care se poate răspunde pe baza întrebărilor frecvente.",
        },
      },
      implementation: "medium",
      timeToValueMonths: {
        low: 1,
        high: 2,
      },
      investmentLevel: 2,
      investmentRon: {
        low: 3000,
        high: 6000,
        mid: 4500,
      },
      opportunityIds: ["ai-assistant"],
      recommended: false,
    },
  ],
  roadmap: [
    {
      key: "foundation",
      startMonth: 1,
      endMonth: 2,
      stage: {
        en: "Foundation",
        ro: "Bazele",
      },
      tag: "essential",
      title: {
        en: "Website fixes and Google visibility",
        ro: "Remedieri pe site și vizibilitate în Google",
      },
      items: [
        {
          en: "Slow first screen on mobile",
          ro: "Primul ecran se încarcă greu pe mobil",
        },
        {
          en: "Visitor tracking without cookie consent",
          ro: "Urmărirea vizitatorilor fără acord pentru cookie-uri",
        },
        {
          en: "Google doesn't get your business details",
          ro: "Google nu primește datele firmei",
        },
        {
          en: "Easier to find on Google and Maps nearby: the Google profile, reviews and a page for each service",
          ro: "Mai ușor de găsit în Google și pe hartă, în zona ta: profilul Google, recenziile și câte o pagină pentru fiecare serviciu",
        },
      ],
      opportunityIds: [],
      websiteCostRon: {
        low: 2700,
        high: 6500,
        mid: 4600,
      },
    },
    {
      key: "automation",
      startMonth: 2,
      endMonth: 3,
      stage: {
        en: "Automation",
        ro: "Automatizare",
      },
      tag: "high-impact",
      title: {
        en: "Automatic booking and reminders",
        ro: "Programări și reamintiri automate",
      },
      items: [
        {
          en: "Automatic appointment reminders",
          ro: "Reamintiri automate pentru programări",
        },
        {
          en: "Online booking with real availability",
          ro: "Programare online cu disponibilitate reală",
        },
        {
          en: "Six-month check-up recalls",
          ro: "Reamintiri pentru controlul la șase luni",
        },
      ],
      opportunityIds: ["appointment-reminders", "online-booking", "recall-reminders"],
    },
    {
      key: "assistant",
      startMonth: 3,
      endMonth: 4,
      stage: {
        en: "AI assistant",
        ro: "Asistent AI",
      },
      tag: "high-impact",
      title: {
        en: "Website and WhatsApp assistant",
        ro: "Asistent pe site și WhatsApp",
      },
      items: [
        {
          en: "AI patient assistant",
          ro: "Asistent AI pentru pacienți",
        },
        {
          en: "Your FAQ, prices and tone of voice prepared for the assistant",
          ro: "Întrebările frecvente, prețurile și stilul de comunicare, pregătite pentru asistent",
        },
        {
          en: "Handover to a person on WhatsApp or email",
          ro: "Preluarea conversației de către un coleg, pe WhatsApp sau e-mail",
        },
      ],
      opportunityIds: ["ai-assistant"],
    },
    {
      key: "growth",
      startMonth: 4,
      endMonth: 6,
      stage: {
        en: "Growth",
        ro: "Creștere",
      },
      tag: "growth",
      title: {
        en: "Reviews",
        ro: "Recenzii",
      },
      items: [
        {
          en: "Review requests after each visit",
          ro: "Cereri de recenzii după fiecare vizită",
        },
      ],
      opportunityIds: ["review-requests"],
    },
  ],
  projection: [
    {
      month: 1,
      cumulativeSavingsRon: {
        low: 0,
        high: 0,
        mid: 0,
      },
      cumulativeCostRon: {
        low: 0,
        high: 0,
        mid: 0,
      },
    },
    {
      month: 2,
      cumulativeSavingsRon: {
        low: 0,
        high: 0,
        mid: 0,
      },
      cumulativeCostRon: {
        low: 5400,
        high: 11000,
        mid: 8200,
      },
    },
    {
      month: 3,
      cumulativeSavingsRon: {
        low: 400,
        high: 880,
        mid: 620,
      },
      cumulativeCostRon: {
        low: 8690,
        high: 17840,
        mid: 13260,
      },
    },
    {
      month: 4,
      cumulativeSavingsRon: {
        low: 1270,
        high: 2820,
        mid: 1970,
      },
      cumulativeCostRon: {
        low: 10300,
        high: 21540,
        mid: 15910,
      },
    },
    {
      month: 5,
      cumulativeSavingsRon: {
        low: 2290,
        high: 5110,
        mid: 3560,
      },
      cumulativeCostRon: {
        low: 10770,
        high: 22940,
        mid: 16840,
      },
    },
    {
      month: 6,
      cumulativeSavingsRon: {
        low: 3400,
        high: 7570,
        mid: 5280,
      },
      cumulativeCostRon: {
        low: 11240,
        high: 24340,
        mid: 17770,
      },
    },
    {
      month: 7,
      cumulativeSavingsRon: {
        low: 4510,
        high: 10030,
        mid: 7000,
      },
      cumulativeCostRon: {
        low: 11710,
        high: 25740,
        mid: 18700,
      },
    },
    {
      month: 8,
      cumulativeSavingsRon: {
        low: 5620,
        high: 12490,
        mid: 8720,
      },
      cumulativeCostRon: {
        low: 12180,
        high: 27140,
        mid: 19630,
      },
    },
    {
      month: 9,
      cumulativeSavingsRon: {
        low: 6730,
        high: 14950,
        mid: 10440,
      },
      cumulativeCostRon: {
        low: 12650,
        high: 28540,
        mid: 20560,
      },
    },
    {
      month: 10,
      cumulativeSavingsRon: {
        low: 7840,
        high: 17410,
        mid: 12160,
      },
      cumulativeCostRon: {
        low: 13120,
        high: 29940,
        mid: 21490,
      },
    },
    {
      month: 11,
      cumulativeSavingsRon: {
        low: 8950,
        high: 19870,
        mid: 13880,
      },
      cumulativeCostRon: {
        low: 13590,
        high: 31340,
        mid: 22420,
      },
    },
    {
      month: 12,
      cumulativeSavingsRon: {
        low: 10060,
        high: 22330,
        mid: 15600,
      },
      cumulativeCostRon: {
        low: 14060,
        high: 32740,
        mid: 23350,
      },
    },
    {
      month: 13,
      cumulativeSavingsRon: {
        low: 11170,
        high: 24790,
        mid: 17320,
      },
      cumulativeCostRon: {
        low: 14530,
        high: 34140,
        mid: 24280,
      },
    },
    {
      month: 14,
      cumulativeSavingsRon: {
        low: 12280,
        high: 27250,
        mid: 19040,
      },
      cumulativeCostRon: {
        low: 15000,
        high: 35540,
        mid: 25210,
      },
    },
    {
      month: 15,
      cumulativeSavingsRon: {
        low: 13390,
        high: 29710,
        mid: 20760,
      },
      cumulativeCostRon: {
        low: 15470,
        high: 36940,
        mid: 26140,
      },
    },
    {
      month: 16,
      cumulativeSavingsRon: {
        low: 14500,
        high: 32170,
        mid: 22480,
      },
      cumulativeCostRon: {
        low: 15940,
        high: 38340,
        mid: 27070,
      },
    },
    {
      month: 17,
      cumulativeSavingsRon: {
        low: 15610,
        high: 34630,
        mid: 24200,
      },
      cumulativeCostRon: {
        low: 16410,
        high: 39740,
        mid: 28000,
      },
    },
    {
      month: 18,
      cumulativeSavingsRon: {
        low: 16720,
        high: 37090,
        mid: 25920,
      },
      cumulativeCostRon: {
        low: 16880,
        high: 41140,
        mid: 28930,
      },
    },
    {
      month: 19,
      cumulativeSavingsRon: {
        low: 17830,
        high: 39550,
        mid: 27640,
      },
      cumulativeCostRon: {
        low: 17350,
        high: 42540,
        mid: 29860,
      },
    },
    {
      month: 20,
      cumulativeSavingsRon: {
        low: 18940,
        high: 42010,
        mid: 29360,
      },
      cumulativeCostRon: {
        low: 17820,
        high: 43940,
        mid: 30790,
      },
    },
    {
      month: 21,
      cumulativeSavingsRon: {
        low: 20050,
        high: 44470,
        mid: 31080,
      },
      cumulativeCostRon: {
        low: 18290,
        high: 45340,
        mid: 31720,
      },
    },
    {
      month: 22,
      cumulativeSavingsRon: {
        low: 21160,
        high: 46930,
        mid: 32800,
      },
      cumulativeCostRon: {
        low: 18760,
        high: 46740,
        mid: 32650,
      },
    },
    {
      month: 23,
      cumulativeSavingsRon: {
        low: 22270,
        high: 49390,
        mid: 34520,
      },
      cumulativeCostRon: {
        low: 19230,
        high: 48140,
        mid: 33580,
      },
    },
    {
      month: 24,
      cumulativeSavingsRon: {
        low: 23380,
        high: 51850,
        mid: 36240,
      },
      cumulativeCostRon: {
        low: 19700,
        high: 49540,
        mid: 34510,
      },
    },
  ],
  offer: {
    planId: "growth",
    title: {
      en: "Growth",
      ro: "Growth",
    },
    why: {
      en: "The plan has 4 stages; Growth covers the guided setup and ongoing support.",
      ro: "Planul are 4 etape; Growth acoperă implementarea ghidată și suportul continuu.",
    },
    includes: [
      {
        en: "2 hours of live consultation on Zoom",
        ro: "2 ore de consultanță live pe Zoom",
      },
      {
        en: "Guided setup of the 4 stages of the plan",
        ro: "Configurare ghidată pentru cele 4 etape din plan",
      },
      {
        en: "Priority scheduling and email support",
        ro: "Programări cu prioritate și suport pe e-mail",
      },
    ],
    priceNote: {
      en: "250 RON a month, plus the setup (fixed price after a call)",
      ro: "250 lei pe lună, plus implementarea (preț fix după discuție)",
    },
  },
  assumptions: {
    hourlyCostRon: 32,
    hourlyCostBasis: {
      en: "1.2 × the gross minimum wage (4,325 lei, HG nr. 146/2026 (Monitorul Oficial, 13.03.2026)) = 5,190 lei a month, plus the 2.25% employer contribution (CAM), over 168 working hours a month = 32 lei an hour. Reception, booking and admin work are paid close to the minimum wage in every sector.",
      ro: "1,2 × salariul minim brut (4.325 lei, HG nr. 146/2026 (Monitorul Oficial, 13.03.2026)) = 5.190 lei pe lună, plus contribuția asiguratorie pentru muncă (CAM) de 2,25%, împărțit la 168 de ore lucrate pe lună = 32 lei pe oră. Munca de recepție, programări și birou e plătită aproape de salariul minim în orice domeniu.",
    },
    teamSize: {
      low: 4,
      high: 9,
    },
    simulation: {
      teamSize: 6,
      hourlyCostRon: 32,
      volumeFactor: 1,
    },
    notes: [
      {
        en: "Team size is an estimate, not data: 4–9 people for a typical dental clinic. Set your real team size in the simulation.",
        ro: "Mărimea echipei e o estimare, nu o cifră reală: 4–9 persoane pentru o afacere de tipul „Clinică stomatologică”. Poți pune numărul real de oameni în simulare.",
      },
      {
        en: "Volumes are typical for a dental clinic of this size, not measured; each automation lists its own.",
        ro: "Volumele sunt tipice pentru o afacere de tipul „Clinică stomatologică” de această mărime, nu sunt măsurate; fiecare automatizare își arată propriile volume.",
      },
      {
        en: "Costs are a one-off setup plus monthly tools from Vortex Hub's price book (RON, excluding VAT); the Vortex Hub plan fee is separate.",
        ro: "Costurile includ implementarea, plătită o singură dată, și instrumentele lunare, conform listei de prețuri Vortex Hub (lei, fără TVA); abonamentul Vortex Hub se plătește separat.",
      },
      {
        en: "Projection: setup is paid when its phase of the plan starts; the hours won back start the month after, at half the first month and in full after that.",
        ro: "Proiecție: implementarea se plătește la începutul etapei din plan; orele câștigate încep din luna următoare, pe jumătate în prima lună și integral după aceea.",
      },
    ],
  },
  disclaimer: {
    en: "Estimates, not guarantees. Based on public data (ANAF, the Trade Register, your website), INS average earnings (July 2026), typical volumes for this kind of business and Vortex's price book. Final figures come from a short discovery call.",
    ro: "Estimări, nu garanții. Calculele folosesc date publice (ANAF, Registrul Comerțului, site-ul tău), câștigul salarial mediu INS (iulie 2026), volume tipice pentru acest tip de afacere și lista de prețuri Vortex. Cifrele finale le stabilim împreună, după o scurtă discuție de evaluare.",
  },
};
