/**
 * Regenerates the scan fixtures from the engine, so the demo (/scan?demo=…),
 * the PDF sample and the design checks always show what the engine produces:
 *
 * - src/lib/scan/fixtures/sample-blueprint.ts: the demo dental clinic in
 *   Timișoara (with a website, audit and competitors). Its inputs (company,
 *   audit, presence, competitors) are kept; everything computed is rebuilt.
 * - src/lib/scan/fixtures/base-case-blueprint.ts: the plan's base case (§3.9),
 *   a dental clinic with no website and no Google profile.
 *
 *   npx tsx scripts/scan/gen-fixtures.ts && npx prettier --write src/lib/scan/fixtures
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { buildRulesBlueprint } from "../../src/lib/scan/blueprint";
import { SAMPLE_BLUEPRINT } from "../../src/lib/scan/fixtures/sample-blueprint";
import type { Blueprint } from "../../src/lib/scan/types";

const fixtures = new URL("../../src/lib/scan/fixtures/", import.meta.url);

function write(file: string, name: string, doc: string, blueprint: Blueprint) {
  const body = `import type { Blueprint } from "../types";

/**
${doc
  .trim()
  .split("\n")
  .map((line) => ` * ${line}`.trimEnd())
  .join("\n")}
 *
 * Generated by scripts/scan/gen-fixtures.ts from the engine: do not edit by
 * hand, run the script again after an engine change.
 */
export const ${name}: Blueprint = ${JSON.stringify(blueprint, null, 2)};
`;
  const path = fileURLToPath(new URL(file, fixtures));
  writeFileSync(path, body);
  console.log(`wrote ${path}`);
}

/* demo: keep the hand-made inputs, rebuild the rest */
const generatedAt = "2026-10-03T09:30:00.000Z";
const sample = buildRulesBlueprint({
  target: { ...SAMPLE_BLUEPRINT.target },
  company: SAMPLE_BLUEPRINT.company,
  audit: SAMPLE_BLUEPRINT.audit,
  presence: SAMPLE_BLUEPRINT.presence,
  competitors: SAMPLE_BLUEPRINT.competitors,
  now: generatedAt,
});
write(
  "sample-blueprint.ts",
  "SAMPLE_BLUEPRINT",
  `A realistic blueprint for designing and testing the scan report and the PDF
without running a scan (a fictional dental clinic in Timișoara, shown as
"Date de exemplu"). Also served at /scan?demo=overview. The ANAF address keeps the
registry's cedilla letters on purpose: the screens fix them with
withCommaBelow (src/lib/scan/localize.ts).`,
  { ...sample, id: "demo-dental-timisoara", generatedAt },
);

/* base case: no website, no Google profile */
const base = buildRulesBlueprint({
  target: { cui: "11111111" },
  company: {
    cui: "11111111",
    name: "CLINICA DENTARA EXEMPLU S.R.L.",
    displayName: "Clinica Dentară Exemplu SRL",
    city: "București",
    county: "București",
    caen: "8623",
    caenLabel: { en: "Dental practice activities", ro: "Activități de asistență stomatologică" },
    sources: ["anaf", "index"],
  },
  presence: { profiles: [{ platform: "google-business", status: "missing" }] },
  businessTypeId: "dental-clinic",
  now: generatedAt,
});
write(
  "base-case-blueprint.ts",
  "BASE_CASE_BLUEPRINT",
  `The plan's base case (UI refresh spec §3.9): a fictional dental clinic with no
website and no Google profile. The site phase, the "site online" milestone
and the excluded website cost all show here; use it with displayPlan() to
check a screen or the PDF against the reference figures.`,
  { ...base, id: "demo-dental-base-case", generatedAt },
);
