/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DigitalProductsRouteImport } from './routes/digital-products'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultancyRouteImport } from './routes/consultancy'
import { Route as AiAutomationRouteImport } from './routes/ai-automation'
import { Route as IndexRouteImport } from './routes/index'

const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalProductsRoute = DigitalProductsRouteImport.update({
  id: '/digital-products',
  path: '/digital-products',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyRoute = ConsultancyRouteImport.update({
  id: '/consultancy',
  path: '/consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/digital-products': typeof DigitalProductsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/digital-products': typeof DigitalProductsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/digital-products': typeof DigitalProductsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-automation'
    | '/consultancy'
    | '/contact'
    | '/dashboard'
    | '/digital-products'
    | '/login'
    | '/portfolio'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/terms'
    | '/websites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-automation'
    | '/consultancy'
    | '/contact'
    | '/dashboard'
    | '/digital-products'
    | '/login'
    | '/portfolio'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/terms'
    | '/websites'
  id:
    | '__root__'
    | '/'
    | '/ai-automation'
    | '/consultancy'
    | '/contact'
    | '/dashboard'
    | '/digital-products'
    | '/login'
    | '/portfolio'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/terms'
    | '/websites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAutomationRoute: typeof AiAutomationRoute
  ConsultancyRoute: typeof ConsultancyRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DigitalProductsRoute: typeof DigitalProductsRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  WebsitesRoute: typeof WebsitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-products': {
      id: '/digital-products'
      path: '/digital-products'
      fullPath: '/digital-products'
      preLoaderRoute: typeof DigitalProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy': {
      id: '/consultancy'
      path: '/consultancy'
      fullPath: '/consultancy'
      preLoaderRoute: typeof ConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automation': {
      id: '/ai-automation'
      path: '/ai-automation'
      fullPath: '/ai-automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAutomationRoute: AiAutomationRoute,
  ConsultancyRoute: ConsultancyRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DigitalProductsRoute: DigitalProductsRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  WebsitesRoute: WebsitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
