/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as DigitalProductsRouteImport } from './routes/digital-products'
import { Route as ConsultancyRouteImport } from './routes/consultancy'
import { Route as AiAutomationRouteImport } from './routes/ai-automation'
import { Route as IndexRouteImport } from './routes/index'

const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalProductsRoute = DigitalProductsRouteImport.update({
  id: '/digital-products',
  path: '/digital-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyRoute = ConsultancyRouteImport.update({
  id: '/consultancy',
  path: '/consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/consultancy': typeof ConsultancyRoute
  '/digital-products': typeof DigitalProductsRoute
  '/services': typeof ServicesRoute
  '/websites': typeof WebsitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/consultancy': typeof ConsultancyRoute
  '/digital-products': typeof DigitalProductsRoute
  '/services': typeof ServicesRoute
  '/websites': typeof WebsitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/consultancy': typeof ConsultancyRoute
  '/digital-products': typeof DigitalProductsRoute
  '/services': typeof ServicesRoute
  '/websites': typeof WebsitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-automation'
    | '/consultancy'
    | '/digital-products'
    | '/services'
    | '/websites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-automation'
    | '/consultancy'
    | '/digital-products'
    | '/services'
    | '/websites'
  id:
    | '__root__'
    | '/'
    | '/ai-automation'
    | '/consultancy'
    | '/digital-products'
    | '/services'
    | '/websites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAutomationRoute: typeof AiAutomationRoute
  ConsultancyRoute: typeof ConsultancyRoute
  DigitalProductsRoute: typeof DigitalProductsRoute
  ServicesRoute: typeof ServicesRoute
  WebsitesRoute: typeof WebsitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-products': {
      id: '/digital-products'
      path: '/digital-products'
      fullPath: '/digital-products'
      preLoaderRoute: typeof DigitalProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy': {
      id: '/consultancy'
      path: '/consultancy'
      fullPath: '/consultancy'
      preLoaderRoute: typeof ConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automation': {
      id: '/ai-automation'
      path: '/ai-automation'
      fullPath: '/ai-automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAutomationRoute: AiAutomationRoute,
  ConsultancyRoute: ConsultancyRoute,
  DigitalProductsRoute: DigitalProductsRoute,
  ServicesRoute: ServicesRoute,
  WebsitesRoute: WebsitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
