// This file is automatically generated. Do not edit it directly.
// Edited by hand (perf): the client is imported on demand, see ./lazy.ts. If Lovable
// regenerates this file, keep the lazy import so supabase-js stays out of the entry bundle.
import { createMiddleware } from "@tanstack/react-start";
import { loadSupabase, mayHaveSession } from "./lazy";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    // No stored session means no token to send: anonymous calls skip supabase-js entirely.
    let token: string | undefined;
    if (mayHaveSession()) {
      const supabase = await loadSupabase();
      const { data } = await supabase.auth.getSession();
      token = data.session?.access_token;
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
